# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_org_credit_wallet_response import EnvelopeOrgCreditWalletResponse

class TestEnvelopeOrgCreditWalletResponse(unittest.TestCase):
    """EnvelopeOrgCreditWalletResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeOrgCreditWalletResponse:
        """Test EnvelopeOrgCreditWalletResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeOrgCreditWalletResponse`
        """
        model = EnvelopeOrgCreditWalletResponse()
        if include_optional:
            return EnvelopeOrgCreditWalletResponse(
                data = zarnite.models.org_credit_wallet_response.OrgCreditWalletResponse(
                    org_id = '', 
                    month = '', 
                    included_credits = 56, 
                    used_credits = 56, 
                    remaining_credits = 56, ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeOrgCreditWalletResponse(
                data = zarnite.models.org_credit_wallet_response.OrgCreditWalletResponse(
                    org_id = '', 
                    month = '', 
                    included_credits = 56, 
                    used_credits = 56, 
                    remaining_credits = 56, ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeOrgCreditWalletResponse(self):
        """Test EnvelopeOrgCreditWalletResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
