# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_voice_runtime_close_response import EnvelopeVoiceRuntimeCloseResponse

class TestEnvelopeVoiceRuntimeCloseResponse(unittest.TestCase):
    """EnvelopeVoiceRuntimeCloseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeVoiceRuntimeCloseResponse:
        """Test EnvelopeVoiceRuntimeCloseResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeVoiceRuntimeCloseResponse`
        """
        model = EnvelopeVoiceRuntimeCloseResponse()
        if include_optional:
            return EnvelopeVoiceRuntimeCloseResponse(
                data = zarnite.models.voice_runtime_close_response.VoiceRuntimeCloseResponse(
                    accepted = True, 
                    session_persisted = True, 
                    analytics_enqueued = True, 
                    billing_enqueued = True, 
                    credit_wallet = { }, ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeVoiceRuntimeCloseResponse(
                data = zarnite.models.voice_runtime_close_response.VoiceRuntimeCloseResponse(
                    accepted = True, 
                    session_persisted = True, 
                    analytics_enqueued = True, 
                    billing_enqueued = True, 
                    credit_wallet = { }, ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeVoiceRuntimeCloseResponse(self):
        """Test EnvelopeVoiceRuntimeCloseResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
