# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_deployment_share_verify_response import EnvelopeDeploymentShareVerifyResponse

class TestEnvelopeDeploymentShareVerifyResponse(unittest.TestCase):
    """EnvelopeDeploymentShareVerifyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeDeploymentShareVerifyResponse:
        """Test EnvelopeDeploymentShareVerifyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeDeploymentShareVerifyResponse`
        """
        model = EnvelopeDeploymentShareVerifyResponse()
        if include_optional:
            return EnvelopeDeploymentShareVerifyResponse(
                data = zarnite.models.deployment_share_verify_response.DeploymentShareVerifyResponse(
                    authorized = True, 
                    learner = { }, 
                    deployment = { }, ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeDeploymentShareVerifyResponse(
                data = zarnite.models.deployment_share_verify_response.DeploymentShareVerifyResponse(
                    authorized = True, 
                    learner = { }, 
                    deployment = { }, ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeDeploymentShareVerifyResponse(self):
        """Test EnvelopeDeploymentShareVerifyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
