# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.agent_performance_response import AgentPerformanceResponse

class TestAgentPerformanceResponse(unittest.TestCase):
    """AgentPerformanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentPerformanceResponse:
        """Test AgentPerformanceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentPerformanceResponse`
        """
        model = AgentPerformanceResponse()
        if include_optional:
            return AgentPerformanceResponse(
                org_id = '',
                agent_id = '',
                sessions = { },
                messages = { },
                errors = 56,
                error_rate = 1.337
            )
        else:
            return AgentPerformanceResponse(
                org_id = '',
                agent_id = '',
                sessions = { },
                messages = { },
                errors = 56,
                error_rate = 1.337,
        )
        """

    def testAgentPerformanceResponse(self):
        """Test AgentPerformanceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
