# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_learner_verify_response import EnvelopeLearnerVerifyResponse

class TestEnvelopeLearnerVerifyResponse(unittest.TestCase):
    """EnvelopeLearnerVerifyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeLearnerVerifyResponse:
        """Test EnvelopeLearnerVerifyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeLearnerVerifyResponse`
        """
        model = EnvelopeLearnerVerifyResponse()
        if include_optional:
            return EnvelopeLearnerVerifyResponse(
                data = zarnite.models.learner_verify_response.LearnerVerifyResponse(
                    valid = True, 
                    id = '', 
                    learner_id = '', 
                    org_id = '', 
                    status = '', ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeLearnerVerifyResponse(
                data = zarnite.models.learner_verify_response.LearnerVerifyResponse(
                    valid = True, 
                    id = '', 
                    learner_id = '', 
                    org_id = '', 
                    status = '', ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeLearnerVerifyResponse(self):
        """Test EnvelopeLearnerVerifyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
