# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.org_rag_session_limit_update_request import OrgRagSessionLimitUpdateRequest

class TestOrgRagSessionLimitUpdateRequest(unittest.TestCase):
    """OrgRagSessionLimitUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrgRagSessionLimitUpdateRequest:
        """Test OrgRagSessionLimitUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrgRagSessionLimitUpdateRequest`
        """
        model = OrgRagSessionLimitUpdateRequest()
        if include_optional:
            return OrgRagSessionLimitUpdateRequest(
                enabled = True,
                monthly_session_limit = 1.0,
                monthly_user_session_limit = 1.0,
                monthly_user_time_limit_minutes = 1.0
            )
        else:
            return OrgRagSessionLimitUpdateRequest(
                enabled = True,
        )
        """

    def testOrgRagSessionLimitUpdateRequest(self):
        """Test OrgRagSessionLimitUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
