# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_api_key_response import EnvelopeApiKeyResponse

class TestEnvelopeApiKeyResponse(unittest.TestCase):
    """EnvelopeApiKeyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeApiKeyResponse:
        """Test EnvelopeApiKeyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeApiKeyResponse`
        """
        model = EnvelopeApiKeyResponse()
        if include_optional:
            return EnvelopeApiKeyResponse(
                data = zarnite.models.api_key_response.ApiKeyResponse(
                    id = '', 
                    org_id = '', 
                    name = '', 
                    prefix = '', 
                    scopes = [
                        ''
                        ], 
                    rate_limit = 56, 
                    is_active = True, 
                    last_used_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    total_requests = 56, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeApiKeyResponse(
                data = zarnite.models.api_key_response.ApiKeyResponse(
                    id = '', 
                    org_id = '', 
                    name = '', 
                    prefix = '', 
                    scopes = [
                        ''
                        ], 
                    rate_limit = 56, 
                    is_active = True, 
                    last_used_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    total_requests = 56, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeApiKeyResponse(self):
        """Test EnvelopeApiKeyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
