# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_list_knowledge_document import EnvelopeListKnowledgeDocument

class TestEnvelopeListKnowledgeDocument(unittest.TestCase):
    """EnvelopeListKnowledgeDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeListKnowledgeDocument:
        """Test EnvelopeListKnowledgeDocument
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeListKnowledgeDocument`
        """
        model = EnvelopeListKnowledgeDocument()
        if include_optional:
            return EnvelopeListKnowledgeDocument(
                data = [
                    zarnite.models.knowledge_document.KnowledgeDocument(
                        document_id = '', 
                        source_file = '', 
                        scope = 'agent', 
                        org_id = '', 
                        agent_id = '', 
                        chunk_count = 56, 
                        uploaded_by = '', 
                        created_at = '', )
                    ],
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeListKnowledgeDocument(
                data = [
                    zarnite.models.knowledge_document.KnowledgeDocument(
                        document_id = '', 
                        source_file = '', 
                        scope = 'agent', 
                        org_id = '', 
                        agent_id = '', 
                        chunk_count = 56, 
                        uploaded_by = '', 
                        created_at = '', )
                    ],
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeListKnowledgeDocument(self):
        """Test EnvelopeListKnowledgeDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
