# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.voice_runtime_bootstrap_response import VoiceRuntimeBootstrapResponse

class TestVoiceRuntimeBootstrapResponse(unittest.TestCase):
    """VoiceRuntimeBootstrapResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoiceRuntimeBootstrapResponse:
        """Test VoiceRuntimeBootstrapResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceRuntimeBootstrapResponse`
        """
        model = VoiceRuntimeBootstrapResponse()
        if include_optional:
            return VoiceRuntimeBootstrapResponse(
                session = zarnite.models.voice_runtime_session_ref.VoiceRuntimeSessionRef(
                    session_id = '', 
                    thread_id = '', 
                    room_name = '', ),
                learner = zarnite.models.voice_runtime_learner_context.VoiceRuntimeLearnerContext(
                    user_id = '', 
                    display_name = '', 
                    email = '', 
                    learner_id = '', 
                    status = '', 
                    cefr_level = '', 
                    preferred_language = '', ),
                agent_runtime = zarnite.models.voice_runtime_agent_context.VoiceRuntimeAgentContext(
                    agent_id = '', 
                    behavior_id = '', 
                    system_prompt = '', 
                    response_language = '', 
                    allowed_languages = [
                        ''
                        ], 
                    voice = { }, 
                    guardrails = { }, 
                    knowledge_base_enabled = True, ),
                history = zarnite.models.voice_runtime_history_context.VoiceRuntimeHistoryContext(
                    summary = '', 
                    recent_turns = [
                        zarnite.models.voice_runtime_history_turn.VoiceRuntimeHistoryTurn(
                            role = '', 
                            text = '', 
                            created_at = '', )
                        ], 
                    recent_threads = [
                        zarnite.models.voice_runtime_history_thread.VoiceRuntimeHistoryThread(
                            thread_id = '', 
                            learner_name = '', 
                            latest_question = '', 
                            latest_answer = '', 
                            last_message_at = '', )
                        ], 
                    feedback = { }, ),
                rag = zarnite.models.voice_runtime_rag_context.VoiceRuntimeRagContext(
                    documents_available = True, 
                    knowledge_scope = [
                        ''
                        ], 
                    agent_document_count = 56, 
                    org_document_count = 56, )
            )
        else:
            return VoiceRuntimeBootstrapResponse(
                session = zarnite.models.voice_runtime_session_ref.VoiceRuntimeSessionRef(
                    session_id = '', 
                    thread_id = '', 
                    room_name = '', ),
                learner = zarnite.models.voice_runtime_learner_context.VoiceRuntimeLearnerContext(
                    user_id = '', 
                    display_name = '', 
                    email = '', 
                    learner_id = '', 
                    status = '', 
                    cefr_level = '', 
                    preferred_language = '', ),
                agent_runtime = zarnite.models.voice_runtime_agent_context.VoiceRuntimeAgentContext(
                    agent_id = '', 
                    behavior_id = '', 
                    system_prompt = '', 
                    response_language = '', 
                    allowed_languages = [
                        ''
                        ], 
                    voice = { }, 
                    guardrails = { }, 
                    knowledge_base_enabled = True, ),
                history = zarnite.models.voice_runtime_history_context.VoiceRuntimeHistoryContext(
                    summary = '', 
                    recent_turns = [
                        zarnite.models.voice_runtime_history_turn.VoiceRuntimeHistoryTurn(
                            role = '', 
                            text = '', 
                            created_at = '', )
                        ], 
                    recent_threads = [
                        zarnite.models.voice_runtime_history_thread.VoiceRuntimeHistoryThread(
                            thread_id = '', 
                            learner_name = '', 
                            latest_question = '', 
                            latest_answer = '', 
                            last_message_at = '', )
                        ], 
                    feedback = { }, ),
                rag = zarnite.models.voice_runtime_rag_context.VoiceRuntimeRagContext(
                    documents_available = True, 
                    knowledge_scope = [
                        ''
                        ], 
                    agent_document_count = 56, 
                    org_document_count = 56, ),
        )
        """

    def testVoiceRuntimeBootstrapResponse(self):
        """Test VoiceRuntimeBootstrapResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
