# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.voice_runtime_learner_context import VoiceRuntimeLearnerContext

class TestVoiceRuntimeLearnerContext(unittest.TestCase):
    """VoiceRuntimeLearnerContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoiceRuntimeLearnerContext:
        """Test VoiceRuntimeLearnerContext
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceRuntimeLearnerContext`
        """
        model = VoiceRuntimeLearnerContext()
        if include_optional:
            return VoiceRuntimeLearnerContext(
                user_id = '',
                display_name = '',
                email = '',
                learner_id = '',
                status = '',
                cefr_level = '',
                preferred_language = ''
            )
        else:
            return VoiceRuntimeLearnerContext(
                user_id = '',
                display_name = '',
                status = '',
        )
        """

    def testVoiceRuntimeLearnerContext(self):
        """Test VoiceRuntimeLearnerContext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
