# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.api.memory_api import MemoryApi


class TestMemoryApi(unittest.TestCase):
    """MemoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MemoryApi()

    def tearDown(self) -> None:
        pass

    def test_memory_search_v1_memory_search_post(self) -> None:
        """Test case for memory_search_v1_memory_search_post

        Memory Search
        """
        pass

    def test_memory_stats_v1_memory_stats_get(self) -> None:
        """Test case for memory_stats_v1_memory_stats_get

        Memory Stats
        """
        pass


if __name__ == '__main__':
    unittest.main()
