# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.learner_activity_event import LearnerActivityEvent

class TestLearnerActivityEvent(unittest.TestCase):
    """LearnerActivityEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LearnerActivityEvent:
        """Test LearnerActivityEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LearnerActivityEvent`
        """
        model = LearnerActivityEvent()
        if include_optional:
            return LearnerActivityEvent(
                session_id = '',
                agent_id = '',
                session_kind = '',
                status = '',
                started_at = '',
                ended_at = '',
                duration_s = 1.337,
                event_count = 56
            )
        else:
            return LearnerActivityEvent(
                session_id = '',
                agent_id = '',
                session_kind = '',
                status = '',
        )
        """

    def testLearnerActivityEvent(self):
        """Test LearnerActivityEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
