# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.api_key_stats_response import ApiKeyStatsResponse

class TestApiKeyStatsResponse(unittest.TestCase):
    """ApiKeyStatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyStatsResponse:
        """Test ApiKeyStatsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyStatsResponse`
        """
        model = ApiKeyStatsResponse()
        if include_optional:
            return ApiKeyStatsResponse(
                org_id = '',
                total_keys = 56,
                active_keys = 56,
                total_requests = 56
            )
        else:
            return ApiKeyStatsResponse(
                org_id = '',
                total_keys = 56,
                active_keys = 56,
                total_requests = 56,
        )
        """

    def testApiKeyStatsResponse(self):
        """Test ApiKeyStatsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
