# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.voice_runtime_bootstrap_request import VoiceRuntimeBootstrapRequest

class TestVoiceRuntimeBootstrapRequest(unittest.TestCase):
    """VoiceRuntimeBootstrapRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoiceRuntimeBootstrapRequest:
        """Test VoiceRuntimeBootstrapRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceRuntimeBootstrapRequest`
        """
        model = VoiceRuntimeBootstrapRequest()
        if include_optional:
            return VoiceRuntimeBootstrapRequest(
                session_id = '',
                org_id = '',
                agent_id = '',
                user_id = '',
                thread_id = '',
                room_name = '',
                channel = 'voice',
                is_preview = True,
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return VoiceRuntimeBootstrapRequest(
                session_id = '',
                org_id = '',
                agent_id = '',
                user_id = '',
                thread_id = '',
        )
        """

    def testVoiceRuntimeBootstrapRequest(self):
        """Test VoiceRuntimeBootstrapRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
