# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.agent_update import AgentUpdate

class TestAgentUpdate(unittest.TestCase):
    """AgentUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentUpdate:
        """Test AgentUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentUpdate`
        """
        model = AgentUpdate()
        if include_optional:
            return AgentUpdate(
                name = '',
                behavior_id = '',
                description = '',
                api_key_id = '',
                assigned_learners = 0.0,
                status = 'active',
                language = '',
                languages = [
                    ''
                    ],
                system_prompt = '',
                tone = '',
                strictness = '',
                guardrails = zarnite.models.guardrails_config.GuardrailsConfig(
                    allowed_languages = [
                        ''
                        ], 
                    blocked_topics = [
                        ''
                        ], 
                    max_response_length = 56, 
                    content_filters = [
                        ''
                        ], 
                    custom_rules = { }, ),
                enable_live_playground = True,
                voice = '',
                enable_knowledge_base = True
            )
        else:
            return AgentUpdate(
        )
        """

    def testAgentUpdate(self):
        """Test AgentUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
