# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.api.agents_api import AgentsApi


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_assign_learner_v1_agents_agent_id_assignments_post(self) -> None:
        """Test case for assign_learner_v1_agents_agent_id_assignments_post

        Assign Learner
        """
        pass

    def test_create_agent_v1_agents_post(self) -> None:
        """Test case for create_agent_v1_agents_post

        Create Agent
        """
        pass

    def test_delete_agent_v1_agents_agent_id_delete(self) -> None:
        """Test case for delete_agent_v1_agents_agent_id_delete

        Delete Agent
        """
        pass

    def test_get_agent_v1_agents_agent_id_get(self) -> None:
        """Test case for get_agent_v1_agents_agent_id_get

        Get Agent
        """
        pass

    def test_list_agents_v1_agents_get(self) -> None:
        """Test case for list_agents_v1_agents_get

        List Agents
        """
        pass

    def test_list_assignments_v1_agents_agent_id_assignments_get(self) -> None:
        """Test case for list_assignments_v1_agents_agent_id_assignments_get

        List Assignments
        """
        pass

    def test_revoke_assignment_v1_agents_agent_id_assignments_learner_id_delete(self) -> None:
        """Test case for revoke_assignment_v1_agents_agent_id_assignments_learner_id_delete

        Revoke Assignment
        """
        pass

    def test_update_agent_v1_agents_agent_id_patch(self) -> None:
        """Test case for update_agent_v1_agents_agent_id_patch

        Update Agent
        """
        pass

    def test_update_agent_v1_agents_agent_id_put(self) -> None:
        """Test case for update_agent_v1_agents_agent_id_put

        Update Agent
        """
        pass


if __name__ == '__main__':
    unittest.main()
