# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.org_overview_response import OrgOverviewResponse

class TestOrgOverviewResponse(unittest.TestCase):
    """OrgOverviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrgOverviewResponse:
        """Test OrgOverviewResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrgOverviewResponse`
        """
        model = OrgOverviewResponse()
        if include_optional:
            return OrgOverviewResponse(
                org_id = '',
                active_users30d = 56,
                total_sessions = 56,
                active_sessions = 56,
                total_messages = 56,
                popular_agents = [
                    { }
                    ]
            )
        else:
            return OrgOverviewResponse(
                org_id = '',
                active_users30d = 56,
                total_sessions = 56,
                active_sessions = 56,
                total_messages = 56,
                popular_agents = [
                    { }
                    ],
        )
        """

    def testOrgOverviewResponse(self):
        """Test OrgOverviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
