# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.api.voice_runtime_api import VoiceRuntimeApi


class TestVoiceRuntimeApi(unittest.TestCase):
    """VoiceRuntimeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VoiceRuntimeApi()

    def tearDown(self) -> None:
        pass

    def test_bootstrap_session_v1_voice_runtime_sessions_bootstrap_post(self) -> None:
        """Test case for bootstrap_session_v1_voice_runtime_sessions_bootstrap_post

        Bootstrap Session
        """
        pass

    def test_close_session_v1_voice_runtime_sessions_session_id_close_post(self) -> None:
        """Test case for close_session_v1_voice_runtime_sessions_session_id_close_post

        Close Session
        """
        pass

    def test_write_feedback_v1_voice_runtime_sessions_session_id_feedback_post(self) -> None:
        """Test case for write_feedback_v1_voice_runtime_sessions_session_id_feedback_post

        Write Feedback
        """
        pass


if __name__ == '__main__':
    unittest.main()
