# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.api.playground_api import PlaygroundApi


class TestPlaygroundApi(unittest.TestCase):
    """PlaygroundApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlaygroundApi()

    def tearDown(self) -> None:
        pass

    def test_bootstrap_session_v1_playground_sessions_post(self) -> None:
        """Test case for bootstrap_session_v1_playground_sessions_post

        Bootstrap Session
        """
        pass

    def test_end_session_v1_playground_sessions_session_id_end_post(self) -> None:
        """Test case for end_session_v1_playground_sessions_session_id_end_post

        End Session
        """
        pass

    def test_mark_activity_v1_playground_sessions_session_id_activity_post(self) -> None:
        """Test case for mark_activity_v1_playground_sessions_session_id_activity_post

        Mark Activity
        """
        pass

    def test_recent_transcripts_v1_playground_transcripts_recent_get(self) -> None:
        """Test case for recent_transcripts_v1_playground_transcripts_recent_get

        Recent Transcripts
        """
        pass

    def test_session_diagnostics_v1_playground_sessions_session_id_diagnostics_get(self) -> None:
        """Test case for session_diagnostics_v1_playground_sessions_session_id_diagnostics_get

        Session Diagnostics
        """
        pass

    def test_session_metrics_v1_playground_sessions_session_id_metrics_get(self) -> None:
        """Test case for session_metrics_v1_playground_sessions_session_id_metrics_get

        Session Metrics
        """
        pass

    def test_session_transcript_v1_playground_sessions_session_id_transcript_get(self) -> None:
        """Test case for session_transcript_v1_playground_sessions_session_id_transcript_get

        Session Transcript
        """
        pass

    def test_supported_voices_v1_playground_voices_get(self) -> None:
        """Test case for supported_voices_v1_playground_voices_get

        Supported Voices
        """
        pass

    def test_voice_lookup_v1_playground_voices_lookup_get(self) -> None:
        """Test case for voice_lookup_v1_playground_voices_lookup_get

        Voice Lookup
        """
        pass


if __name__ == '__main__':
    unittest.main()
