# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.voice_runtime_close_request import VoiceRuntimeCloseRequest

class TestVoiceRuntimeCloseRequest(unittest.TestCase):
    """VoiceRuntimeCloseRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoiceRuntimeCloseRequest:
        """Test VoiceRuntimeCloseRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceRuntimeCloseRequest`
        """
        model = VoiceRuntimeCloseRequest()
        if include_optional:
            return VoiceRuntimeCloseRequest(
                event_id = '',
                session_id = '',
                org_id = '',
                agent_id = '',
                user_id = '',
                thread_id = '',
                room_name = '',
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ended_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                duration_seconds = 1.337,
                status = 'completed',
                usage = zarnite.models.voice_runtime_usage_payload.VoiceRuntimeUsagePayload(
                    input_tokens = 56, 
                    output_tokens = 56, 
                    total_tokens = 56, 
                    voice_seconds = 1.337, ),
                transcript = zarnite.models.voice_runtime_transcript_payload.VoiceRuntimeTranscriptPayload(
                    messages = [
                        zarnite.models.voice_runtime_transcript_message.VoiceRuntimeTranscriptMessage(
                            role = '', 
                            text = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], ),
                final_feedback = zarnite.models.voice_runtime_final_feedback.VoiceRuntimeFinalFeedback(
                    confidence_score = 1.337, 
                    cefr_level = '', 
                    recommendation = '', 
                    strengths = [
                        ''
                        ], 
                    weaknesses = [
                        ''
                        ], )
            )
        else:
            return VoiceRuntimeCloseRequest(
                event_id = '',
                session_id = '',
                org_id = '',
                agent_id = '',
                user_id = '',
                thread_id = '',
        )
        """

    def testVoiceRuntimeCloseRequest(self):
        """Test VoiceRuntimeCloseRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
