# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.api.routing_api import RoutingApi


class TestRoutingApi(unittest.TestCase):
    """RoutingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoutingApi()

    def tearDown(self) -> None:
        pass

    def test_get_org_config_v1_routing_org_config_get(self) -> None:
        """Test case for get_org_config_v1_routing_org_config_get

        Get Org Config
        """
        pass

    def test_get_user_category_v1_routing_user_category_get(self) -> None:
        """Test case for get_user_category_v1_routing_user_category_get

        Get User Category
        """
        pass

    def test_update_org_config_v1_routing_org_config_put(self) -> None:
        """Test case for update_org_config_v1_routing_org_config_put

        Update Org Config
        """
        pass

    def test_update_user_category_v1_routing_user_category_put(self) -> None:
        """Test case for update_user_category_v1_routing_user_category_put

        Update User Category
        """
        pass


if __name__ == '__main__':
    unittest.main()
