# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.agent_response import AgentResponse

class TestAgentResponse(unittest.TestCase):
    """AgentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentResponse:
        """Test AgentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentResponse`
        """
        model = AgentResponse()
        if include_optional:
            return AgentResponse(
                id = '',
                org_id = '',
                name = '',
                behavior_id = '',
                behavior = zarnite.models.behavior_response.BehaviorResponse(
                    id = '', 
                    org_id = '', 
                    name = '', 
                    description = '', 
                    system_prompt = '', 
                    tone = '', 
                    strictness = '', 
                    language = '', 
                    languages = [
                        ''
                        ], 
                    guardrails = { }, 
                    voice = '', 
                    is_default = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                description = '',
                api_key_id = '',
                assigned_learners = 56,
                status = 'active',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                language = '',
                languages = [
                    ''
                    ],
                system_prompt = '',
                tone = '',
                strictness = '',
                guardrails = { },
                enable_live_playground = True,
                voice = '',
                enable_knowledge_base = True
            )
        else:
            return AgentResponse(
                id = '',
                org_id = '',
                name = '',
                status = 'active',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testAgentResponse(self):
        """Test AgentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
