# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_org_overview_response import EnvelopeOrgOverviewResponse

class TestEnvelopeOrgOverviewResponse(unittest.TestCase):
    """EnvelopeOrgOverviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeOrgOverviewResponse:
        """Test EnvelopeOrgOverviewResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeOrgOverviewResponse`
        """
        model = EnvelopeOrgOverviewResponse()
        if include_optional:
            return EnvelopeOrgOverviewResponse(
                data = zarnite.models.org_overview_response.OrgOverviewResponse(
                    org_id = '', 
                    active_users30d = 56, 
                    total_sessions = 56, 
                    active_sessions = 56, 
                    total_messages = 56, 
                    popular_agents = [
                        { }
                        ], ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeOrgOverviewResponse(
                data = zarnite.models.org_overview_response.OrgOverviewResponse(
                    org_id = '', 
                    active_users30d = 56, 
                    total_sessions = 56, 
                    active_sessions = 56, 
                    total_messages = 56, 
                    popular_agents = [
                        { }
                        ], ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeOrgOverviewResponse(self):
        """Test EnvelopeOrgOverviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
