# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_dashboard_overview_response import EnvelopeDashboardOverviewResponse

class TestEnvelopeDashboardOverviewResponse(unittest.TestCase):
    """EnvelopeDashboardOverviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeDashboardOverviewResponse:
        """Test EnvelopeDashboardOverviewResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeDashboardOverviewResponse`
        """
        model = EnvelopeDashboardOverviewResponse()
        if include_optional:
            return EnvelopeDashboardOverviewResponse(
                data = zarnite.models.dashboard_overview_response.DashboardOverviewResponse(
                    kpis = { }, 
                    system_status = { }, 
                    usage_trends = { }, 
                    progress_distribution = [
                        { }
                        ], 
                    progression_delta_pct = 1.337, 
                    progression_summary = '', 
                    agent_activity = [
                        { }
                        ], 
                    top_error = { }, ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeDashboardOverviewResponse(
                data = zarnite.models.dashboard_overview_response.DashboardOverviewResponse(
                    kpis = { }, 
                    system_status = { }, 
                    usage_trends = { }, 
                    progress_distribution = [
                        { }
                        ], 
                    progression_delta_pct = 1.337, 
                    progression_summary = '', 
                    agent_activity = [
                        { }
                        ], 
                    top_error = { }, ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeDashboardOverviewResponse(self):
        """Test EnvelopeDashboardOverviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
