# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_learner_stats_response import EnvelopeLearnerStatsResponse

class TestEnvelopeLearnerStatsResponse(unittest.TestCase):
    """EnvelopeLearnerStatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeLearnerStatsResponse:
        """Test EnvelopeLearnerStatsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeLearnerStatsResponse`
        """
        model = EnvelopeLearnerStatsResponse()
        if include_optional:
            return EnvelopeLearnerStatsResponse(
                data = zarnite.models.learner_stats_response.LearnerStatsResponse(
                    total_sessions = 56, 
                    avg_duration_minutes = 1.337, 
                    avg_latency_ms = 1.337, 
                    est_inference_cost_per_session = 1.337, 
                    total_tokens_used = 56, 
                    last_session_at = '', ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeLearnerStatsResponse(
                data = zarnite.models.learner_stats_response.LearnerStatsResponse(
                    total_sessions = 56, 
                    avg_duration_minutes = 1.337, 
                    avg_latency_ms = 1.337, 
                    est_inference_cost_per_session = 1.337, 
                    total_tokens_used = 56, 
                    last_session_at = '', ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeLearnerStatsResponse(self):
        """Test EnvelopeLearnerStatsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
