# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.knowledge_document import KnowledgeDocument

class TestKnowledgeDocument(unittest.TestCase):
    """KnowledgeDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KnowledgeDocument:
        """Test KnowledgeDocument
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KnowledgeDocument`
        """
        model = KnowledgeDocument()
        if include_optional:
            return KnowledgeDocument(
                document_id = '',
                source_file = '',
                scope = 'agent',
                org_id = '',
                agent_id = '',
                chunk_count = 56,
                uploaded_by = '',
                created_at = ''
            )
        else:
            return KnowledgeDocument(
                document_id = '',
                source_file = '',
                scope = 'agent',
                org_id = '',
                chunk_count = 56,
        )
        """

    def testKnowledgeDocument(self):
        """Test KnowledgeDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
