# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_list_playground_session_transcript_response import EnvelopeListPlaygroundSessionTranscriptResponse

class TestEnvelopeListPlaygroundSessionTranscriptResponse(unittest.TestCase):
    """EnvelopeListPlaygroundSessionTranscriptResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeListPlaygroundSessionTranscriptResponse:
        """Test EnvelopeListPlaygroundSessionTranscriptResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeListPlaygroundSessionTranscriptResponse`
        """
        model = EnvelopeListPlaygroundSessionTranscriptResponse()
        if include_optional:
            return EnvelopeListPlaygroundSessionTranscriptResponse(
                data = [
                    zarnite.models.playground_session_transcript_response.PlaygroundSessionTranscriptResponse(
                        session_id = '', 
                        thread_id = '', 
                        session_kind = '', 
                        status = '', 
                        started_at = '', 
                        ended_at = '', 
                        last_activity_at = '', 
                        livekit_room_name = '', 
                        messages = [
                            zarnite.models.playground_transcript_message.PlaygroundTranscriptMessage(
                                role = '', 
                                content = '', 
                                created_at = '', )
                            ], )
                    ],
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeListPlaygroundSessionTranscriptResponse(
                data = [
                    zarnite.models.playground_session_transcript_response.PlaygroundSessionTranscriptResponse(
                        session_id = '', 
                        thread_id = '', 
                        session_kind = '', 
                        status = '', 
                        started_at = '', 
                        ended_at = '', 
                        last_activity_at = '', 
                        livekit_room_name = '', 
                        messages = [
                            zarnite.models.playground_transcript_message.PlaygroundTranscriptMessage(
                                role = '', 
                                content = '', 
                                created_at = '', )
                            ], )
                    ],
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeListPlaygroundSessionTranscriptResponse(self):
        """Test EnvelopeListPlaygroundSessionTranscriptResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
