# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.learner_summary_response import LearnerSummaryResponse

class TestLearnerSummaryResponse(unittest.TestCase):
    """LearnerSummaryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LearnerSummaryResponse:
        """Test LearnerSummaryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LearnerSummaryResponse`
        """
        model = LearnerSummaryResponse()
        if include_optional:
            return LearnerSummaryResponse(
                learner_id = '',
                learner_name = '',
                personalized_message = '',
                recent_topics = [
                    ''
                    ],
                current_score = 56,
                cefr_level = ''
            )
        else:
            return LearnerSummaryResponse(
                learner_id = '',
                learner_name = '',
                personalized_message = '',
                current_score = 56,
                cefr_level = '',
        )
        """

    def testLearnerSummaryResponse(self):
        """Test LearnerSummaryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
