# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.dashboard_overview_response import DashboardOverviewResponse

class TestDashboardOverviewResponse(unittest.TestCase):
    """DashboardOverviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DashboardOverviewResponse:
        """Test DashboardOverviewResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DashboardOverviewResponse`
        """
        model = DashboardOverviewResponse()
        if include_optional:
            return DashboardOverviewResponse(
                kpis = { },
                system_status = { },
                usage_trends = { },
                progress_distribution = [
                    { }
                    ],
                progression_delta_pct = 1.337,
                progression_summary = '',
                agent_activity = [
                    { }
                    ],
                top_error = { }
            )
        else:
            return DashboardOverviewResponse(
                kpis = { },
                system_status = { },
                usage_trends = { },
        )
        """

    def testDashboardOverviewResponse(self):
        """Test DashboardOverviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
