# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.playground_public_session_request import PlaygroundPublicSessionRequest

class TestPlaygroundPublicSessionRequest(unittest.TestCase):
    """PlaygroundPublicSessionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlaygroundPublicSessionRequest:
        """Test PlaygroundPublicSessionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlaygroundPublicSessionRequest`
        """
        model = PlaygroundPublicSessionRequest()
        if include_optional:
            return PlaygroundPublicSessionRequest(
                org_id = '',
                name = '',
                description = '',
                system_prompt = '',
                tone = '',
                strictness = '',
                language = '',
                languages = [
                    ''
                    ],
                voice = zarnite.models.playground_voice_config.PlaygroundVoiceConfig(
                    voice_id = '', 
                    locale = '', 
                    pitch = 1.337, 
                    speaking_rate = 1.337, ),
                guardrails = zarnite.models.guardrails_config.GuardrailsConfig(
                    allowed_languages = [
                        ''
                        ], 
                    blocked_topics = [
                        ''
                        ], 
                    max_response_length = 56, 
                    content_filters = [
                        ''
                        ], 
                    custom_rules = { }, ),
                behavior = { },
                preview_agent_id = '',
                enable_knowledge_base = True,
                knowledge_base_agent_ids = [
                    ''
                    ],
                learner_id = '',
                thread_id = '',
                max_duration_s = 180.0,
                client = zarnite.models.playground_client_meta.PlaygroundClientMeta(
                    source = 'web_playground', 
                    user_agent = '', 
                    debug_panel = True, )
            )
        else:
            return PlaygroundPublicSessionRequest(
        )
        """

    def testPlaygroundPublicSessionRequest(self):
        """Test PlaygroundPublicSessionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
