# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.playground_latency_diagnostics import PlaygroundLatencyDiagnostics

class TestPlaygroundLatencyDiagnostics(unittest.TestCase):
    """PlaygroundLatencyDiagnostics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlaygroundLatencyDiagnostics:
        """Test PlaygroundLatencyDiagnostics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlaygroundLatencyDiagnostics`
        """
        model = PlaygroundLatencyDiagnostics()
        if include_optional:
            return PlaygroundLatencyDiagnostics(
                avg_turn_latency_ms = 1.337,
                avg_rag_latency_ms = 1.337,
                completed_turns = 56,
                rag_calls = 56
            )
        else:
            return PlaygroundLatencyDiagnostics(
        )
        """

    def testPlaygroundLatencyDiagnostics(self):
        """Test PlaygroundLatencyDiagnostics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
