# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.playground_voice_config_input import PlaygroundVoiceConfigInput

class TestPlaygroundVoiceConfigInput(unittest.TestCase):
    """PlaygroundVoiceConfigInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlaygroundVoiceConfigInput:
        """Test PlaygroundVoiceConfigInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlaygroundVoiceConfigInput`
        """
        model = PlaygroundVoiceConfigInput()
        if include_optional:
            return PlaygroundVoiceConfigInput(
                voice_id = '',
                locale = '',
                pitch = 1.337,
                speaking_rate = 1.337
            )
        else:
            return PlaygroundVoiceConfigInput(
        )
        """

    def testPlaygroundVoiceConfigInput(self):
        """Test PlaygroundVoiceConfigInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
