# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.memory_search_request import MemorySearchRequest

class TestMemorySearchRequest(unittest.TestCase):
    """MemorySearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MemorySearchRequest:
        """Test MemorySearchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MemorySearchRequest`
        """
        model = MemorySearchRequest()
        if include_optional:
            return MemorySearchRequest(
                question = '',
                org_id = '',
                agent_id = '',
                user_id = '',
                thread_id = '',
                step_size = 1.0
            )
        else:
            return MemorySearchRequest(
                question = '',
                org_id = '',
                agent_id = '',
                user_id = '',
        )
        """

    def testMemorySearchRequest(self):
        """Test MemorySearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
