# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.learner_feedback_metric import LearnerFeedbackMetric

class TestLearnerFeedbackMetric(unittest.TestCase):
    """LearnerFeedbackMetric unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LearnerFeedbackMetric:
        """Test LearnerFeedbackMetric
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LearnerFeedbackMetric`
        """
        model = LearnerFeedbackMetric()
        if include_optional:
            return LearnerFeedbackMetric(
                current = 56,
                previous = 56,
                delta = 56,
                direction = 'up'
            )
        else:
            return LearnerFeedbackMetric(
                current = 56,
                previous = 56,
                delta = 56,
                direction = 'up',
        )
        """

    def testLearnerFeedbackMetric(self):
        """Test LearnerFeedbackMetric"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
