# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_api_key_stats_response import EnvelopeApiKeyStatsResponse

class TestEnvelopeApiKeyStatsResponse(unittest.TestCase):
    """EnvelopeApiKeyStatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeApiKeyStatsResponse:
        """Test EnvelopeApiKeyStatsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeApiKeyStatsResponse`
        """
        model = EnvelopeApiKeyStatsResponse()
        if include_optional:
            return EnvelopeApiKeyStatsResponse(
                data = zarnite.models.api_key_stats_response.ApiKeyStatsResponse(
                    org_id = '', 
                    total_keys = 56, 
                    active_keys = 56, 
                    total_requests = 56, ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeApiKeyStatsResponse(
                data = zarnite.models.api_key_stats_response.ApiKeyStatsResponse(
                    org_id = '', 
                    total_keys = 56, 
                    active_keys = 56, 
                    total_requests = 56, ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeApiKeyStatsResponse(self):
        """Test EnvelopeApiKeyStatsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
