# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_list_knowledge_upload_response import EnvelopeListKnowledgeUploadResponse

class TestEnvelopeListKnowledgeUploadResponse(unittest.TestCase):
    """EnvelopeListKnowledgeUploadResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeListKnowledgeUploadResponse:
        """Test EnvelopeListKnowledgeUploadResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeListKnowledgeUploadResponse`
        """
        model = EnvelopeListKnowledgeUploadResponse()
        if include_optional:
            return EnvelopeListKnowledgeUploadResponse(
                data = [
                    zarnite.models.knowledge_upload_response.KnowledgeUploadResponse(
                        status = '', 
                        scope = 'agent', 
                        org_id = '', 
                        agent_id = '', 
                        kb_target_agent_id = '', 
                        user_id = '', 
                        file = '', 
                        chunks_indexed = 56, 
                        chunk_limit_applied = True, )
                    ],
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeListKnowledgeUploadResponse(
                data = [
                    zarnite.models.knowledge_upload_response.KnowledgeUploadResponse(
                        status = '', 
                        scope = 'agent', 
                        org_id = '', 
                        agent_id = '', 
                        kb_target_agent_id = '', 
                        user_id = '', 
                        file = '', 
                        chunks_indexed = 56, 
                        chunk_limit_applied = True, )
                    ],
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeListKnowledgeUploadResponse(self):
        """Test EnvelopeListKnowledgeUploadResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
