# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.learner_longitudinal_feedback_response import LearnerLongitudinalFeedbackResponse

class TestLearnerLongitudinalFeedbackResponse(unittest.TestCase):
    """LearnerLongitudinalFeedbackResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LearnerLongitudinalFeedbackResponse:
        """Test LearnerLongitudinalFeedbackResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LearnerLongitudinalFeedbackResponse`
        """
        model = LearnerLongitudinalFeedbackResponse()
        if include_optional:
            return LearnerLongitudinalFeedbackResponse(
                learner_id = '',
                learner_name = '',
                sessions_analyzed = 56,
                conversation_window = '',
                narrative = '',
                metrics = zarnite.models.learner_feedback_metrics.LearnerFeedbackMetrics(
                    grammar_accuracy = null, 
                    fluency = null, 
                    vocab_range = null, 
                    contextual_use = null, ),
                strengths = [
                    ''
                    ],
                improvement_areas = [
                    ''
                    ],
                recommended_next_step = '',
                recent_topics = [
                    ''
                    ],
                generated_at = '',
                evaluation_mode = '',
                rubric_type = '',
                rubric_reasoning = '',
                evaluation_criteria = [
                    {
                        'key' : ''
                        }
                    ],
                progression_comparison = { }
            )
        else:
            return LearnerLongitudinalFeedbackResponse(
                learner_id = '',
                learner_name = '',
                sessions_analyzed = 56,
                conversation_window = '',
                narrative = '',
                metrics = zarnite.models.learner_feedback_metrics.LearnerFeedbackMetrics(
                    grammar_accuracy = null, 
                    fluency = null, 
                    vocab_range = null, 
                    contextual_use = null, ),
                recommended_next_step = '',
                generated_at = '',
        )
        """

    def testLearnerLongitudinalFeedbackResponse(self):
        """Test LearnerLongitudinalFeedbackResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
