# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.voice_runtime_history_context import VoiceRuntimeHistoryContext

class TestVoiceRuntimeHistoryContext(unittest.TestCase):
    """VoiceRuntimeHistoryContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoiceRuntimeHistoryContext:
        """Test VoiceRuntimeHistoryContext
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceRuntimeHistoryContext`
        """
        model = VoiceRuntimeHistoryContext()
        if include_optional:
            return VoiceRuntimeHistoryContext(
                summary = '',
                recent_turns = [
                    zarnite.models.voice_runtime_history_turn.VoiceRuntimeHistoryTurn(
                        role = '', 
                        text = '', 
                        created_at = '', )
                    ],
                recent_threads = [
                    zarnite.models.voice_runtime_history_thread.VoiceRuntimeHistoryThread(
                        thread_id = '', 
                        learner_name = '', 
                        latest_question = '', 
                        latest_answer = '', 
                        last_message_at = '', )
                    ],
                feedback = { }
            )
        else:
            return VoiceRuntimeHistoryContext(
        )
        """

    def testVoiceRuntimeHistoryContext(self):
        """Test VoiceRuntimeHistoryContext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
