# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.memory_search_response import MemorySearchResponse

class TestMemorySearchResponse(unittest.TestCase):
    """MemorySearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MemorySearchResponse:
        """Test MemorySearchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MemorySearchResponse`
        """
        model = MemorySearchResponse()
        if include_optional:
            return MemorySearchResponse(
                kb_docs_retrieved = 56,
                memory_docs_retrieved = 56,
                context_tokens_used = 56,
                context_token_budget = 56,
                pricing_tier = '',
                effective_step_size = 56,
                thread_scope_applied = True,
                resolved_thread_id = '',
                kb_context_preview = '',
                memory_context_preview = '',
                kb_hits = [
                    zarnite.models.doc_hit.DocHit(
                        source_file = '', 
                        scope = '', 
                        relevance_score = 1.337, 
                        preview = '', 
                        metadata = { }, )
                    ],
                memory_hits = [
                    zarnite.models.doc_hit.DocHit(
                        source_file = '', 
                        scope = '', 
                        relevance_score = 1.337, 
                        preview = '', 
                        metadata = { }, )
                    ]
            )
        else:
            return MemorySearchResponse(
                kb_docs_retrieved = 56,
                memory_docs_retrieved = 56,
                context_tokens_used = 56,
                context_token_budget = 56,
                pricing_tier = '',
                effective_step_size = 56,
                thread_scope_applied = True,
                kb_context_preview = '',
                memory_context_preview = '',
        )
        """

    def testMemorySearchResponse(self):
        """Test MemorySearchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
