# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.api.api_keys_api import APIKeysApi


class TestAPIKeysApi(unittest.TestCase):
    """APIKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = APIKeysApi()

    def tearDown(self) -> None:
        pass

    def test_api_key_stats_v1_api_keys_stats_get(self) -> None:
        """Test case for api_key_stats_v1_api_keys_stats_get

        Api Key Stats
        """
        pass

    def test_create_api_key_v1_api_keys_post(self) -> None:
        """Test case for create_api_key_v1_api_keys_post

        Create Api Key
        """
        pass

    def test_list_api_keys_v1_api_keys_get(self) -> None:
        """Test case for list_api_keys_v1_api_keys_get

        List Api Keys
        """
        pass

    def test_revoke_api_key_v1_api_keys_key_id_delete(self) -> None:
        """Test case for revoke_api_key_v1_api_keys_key_id_delete

        Revoke Api Key
        """
        pass

    def test_update_api_key_v1_api_keys_key_id_put(self) -> None:
        """Test case for update_api_key_v1_api_keys_key_id_put

        Update Api Key
        """
        pass


if __name__ == '__main__':
    unittest.main()
