# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_api_key_create_response import EnvelopeApiKeyCreateResponse

class TestEnvelopeApiKeyCreateResponse(unittest.TestCase):
    """EnvelopeApiKeyCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeApiKeyCreateResponse:
        """Test EnvelopeApiKeyCreateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeApiKeyCreateResponse`
        """
        model = EnvelopeApiKeyCreateResponse()
        if include_optional:
            return EnvelopeApiKeyCreateResponse(
                data = zarnite.models.api_key_create_response.ApiKeyCreateResponse(
                    id = '', 
                    org_id = '', 
                    name = '', 
                    prefix = '', 
                    raw_key = '', 
                    scopes = [
                        ''
                        ], 
                    rate_limit = 56, 
                    is_active = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeApiKeyCreateResponse(
                data = zarnite.models.api_key_create_response.ApiKeyCreateResponse(
                    id = '', 
                    org_id = '', 
                    name = '', 
                    prefix = '', 
                    raw_key = '', 
                    scopes = [
                        ''
                        ], 
                    rate_limit = 56, 
                    is_active = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeApiKeyCreateResponse(self):
        """Test EnvelopeApiKeyCreateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
