# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.voice_runtime_agent_context import VoiceRuntimeAgentContext

class TestVoiceRuntimeAgentContext(unittest.TestCase):
    """VoiceRuntimeAgentContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoiceRuntimeAgentContext:
        """Test VoiceRuntimeAgentContext
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceRuntimeAgentContext`
        """
        model = VoiceRuntimeAgentContext()
        if include_optional:
            return VoiceRuntimeAgentContext(
                agent_id = '',
                behavior_id = '',
                system_prompt = '',
                response_language = '',
                allowed_languages = [
                    ''
                    ],
                voice = { },
                guardrails = { },
                knowledge_base_enabled = True
            )
        else:
            return VoiceRuntimeAgentContext(
                agent_id = '',
        )
        """

    def testVoiceRuntimeAgentContext(self):
        """Test VoiceRuntimeAgentContext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
