# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.api.deployments_api import DeploymentsApi


class TestDeploymentsApi(unittest.TestCase):
    """DeploymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeploymentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_deployment_v1_deployments_post(self) -> None:
        """Test case for create_deployment_v1_deployments_post

        Create Deployment
        """
        pass

    def test_delete_deployment_v1_deployments_deploy_id_delete(self) -> None:
        """Test case for delete_deployment_v1_deployments_deploy_id_delete

        Delete Deployment
        """
        pass

    def test_list_deployments_v1_deployments_get(self) -> None:
        """Test case for list_deployments_v1_deployments_get

        List Deployments
        """
        pass

    def test_resolve_share_v1_deployments_share_share_id_get(self) -> None:
        """Test case for resolve_share_v1_deployments_share_share_id_get

        Resolve Share
        """
        pass

    def test_update_deployment_v1_deployments_deploy_id_put(self) -> None:
        """Test case for update_deployment_v1_deployments_deploy_id_put

        Update Deployment
        """
        pass

    def test_verify_share_access_v1_deployments_share_share_id_verify_post(self) -> None:
        """Test case for verify_share_access_v1_deployments_share_share_id_verify_post

        Verify Share Access
        """
        pass


if __name__ == '__main__':
    unittest.main()
