# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.voice_runtime_feedback_payload import VoiceRuntimeFeedbackPayload

class TestVoiceRuntimeFeedbackPayload(unittest.TestCase):
    """VoiceRuntimeFeedbackPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoiceRuntimeFeedbackPayload:
        """Test VoiceRuntimeFeedbackPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoiceRuntimeFeedbackPayload`
        """
        model = VoiceRuntimeFeedbackPayload()
        if include_optional:
            return VoiceRuntimeFeedbackPayload(
                kind = '',
                narrative = '',
                recommendation = '',
                confidence_score = 1.337,
                cefr_level = '',
                strengths = [
                    ''
                    ],
                weaknesses = [
                    ''
                    ],
                details = { }
            )
        else:
            return VoiceRuntimeFeedbackPayload(
                kind = '',
        )
        """

    def testVoiceRuntimeFeedbackPayload(self):
        """Test VoiceRuntimeFeedbackPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
