# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.api.usage_billing_api import UsageBillingApi


class TestUsageBillingApi(unittest.TestCase):
    """UsageBillingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsageBillingApi()

    def tearDown(self) -> None:
        pass

    def test_get_org_credits_v1_usage_credits_get(self) -> None:
        """Test case for get_org_credits_v1_usage_credits_get

        Get Org Credits
        """
        pass

    def test_get_org_rag_session_limit_v1_usage_rag_session_limit_get(self) -> None:
        """Test case for get_org_rag_session_limit_v1_usage_rag_session_limit_get

        Get Org Rag Session Limit
        """
        pass

    def test_get_org_usage_v1_usage_get(self) -> None:
        """Test case for get_org_usage_v1_usage_get

        Get Org Usage
        """
        pass

    def test_get_usage_logs_v1_usage_logs_get(self) -> None:
        """Test case for get_usage_logs_v1_usage_logs_get

        Get Usage Logs
        """
        pass

    def test_update_org_credits_v1_usage_credits_put(self) -> None:
        """Test case for update_org_credits_v1_usage_credits_put

        Update Org Credits
        """
        pass

    def test_update_org_rag_session_limit_v1_usage_rag_session_limit_put(self) -> None:
        """Test case for update_org_rag_session_limit_v1_usage_rag_session_limit_put

        Update Org Rag Session Limit
        """
        pass


if __name__ == '__main__':
    unittest.main()
