# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.api.behaviors_api import BehaviorsApi


class TestBehaviorsApi(unittest.TestCase):
    """BehaviorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BehaviorsApi()

    def tearDown(self) -> None:
        pass

    def test_create_behavior_v1_behaviors_post(self) -> None:
        """Test case for create_behavior_v1_behaviors_post

        Create Behavior
        """
        pass

    def test_delete_behavior_v1_behaviors_behavior_id_delete(self) -> None:
        """Test case for delete_behavior_v1_behaviors_behavior_id_delete

        Delete Behavior
        """
        pass

    def test_get_behavior_v1_behaviors_behavior_id_get(self) -> None:
        """Test case for get_behavior_v1_behaviors_behavior_id_get

        Get Behavior
        """
        pass

    def test_list_behaviors_v1_behaviors_get(self) -> None:
        """Test case for list_behaviors_v1_behaviors_get

        List Behaviors
        """
        pass

    def test_update_behavior_v1_behaviors_behavior_id_patch(self) -> None:
        """Test case for update_behavior_v1_behaviors_behavior_id_patch

        Update Behavior
        """
        pass

    def test_update_behavior_v1_behaviors_behavior_id_put(self) -> None:
        """Test case for update_behavior_v1_behaviors_behavior_id_put

        Update Behavior
        """
        pass


if __name__ == '__main__':
    unittest.main()
