# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.playground_session_request import PlaygroundSessionRequest

class TestPlaygroundSessionRequest(unittest.TestCase):
    """PlaygroundSessionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlaygroundSessionRequest:
        """Test PlaygroundSessionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlaygroundSessionRequest`
        """
        model = PlaygroundSessionRequest()
        if include_optional:
            return PlaygroundSessionRequest(
                org_id = '',
                agent_id = '',
                mode = 'debug',
                playground = True,
                learner_id = '',
                thread_id = '',
                resume_session_id = '',
                language = '',
                voice = zarnite.models.playground_voice_config.PlaygroundVoiceConfig(
                    voice_id = '', 
                    locale = '', 
                    pitch = 1.337, 
                    speaking_rate = 1.337, ),
                client = zarnite.models.playground_client_meta.PlaygroundClientMeta(
                    source = 'web_playground', 
                    user_agent = '', 
                    debug_panel = True, )
            )
        else:
            return PlaygroundSessionRequest(
                org_id = '',
                agent_id = '',
        )
        """

    def testPlaygroundSessionRequest(self):
        """Test PlaygroundSessionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
