# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_playground_activity_response import EnvelopePlaygroundActivityResponse

class TestEnvelopePlaygroundActivityResponse(unittest.TestCase):
    """EnvelopePlaygroundActivityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopePlaygroundActivityResponse:
        """Test EnvelopePlaygroundActivityResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopePlaygroundActivityResponse`
        """
        model = EnvelopePlaygroundActivityResponse()
        if include_optional:
            return EnvelopePlaygroundActivityResponse(
                data = zarnite.models.playground_activity_response.PlaygroundActivityResponse(
                    session_id = '', 
                    status = '', 
                    last_activity_at = '', ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopePlaygroundActivityResponse(
                data = zarnite.models.playground_activity_response.PlaygroundActivityResponse(
                    session_id = '', 
                    status = '', 
                    last_activity_at = '', ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopePlaygroundActivityResponse(self):
        """Test EnvelopePlaygroundActivityResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
