# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_playground_voice_lookup_response import EnvelopePlaygroundVoiceLookupResponse

class TestEnvelopePlaygroundVoiceLookupResponse(unittest.TestCase):
    """EnvelopePlaygroundVoiceLookupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopePlaygroundVoiceLookupResponse:
        """Test EnvelopePlaygroundVoiceLookupResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopePlaygroundVoiceLookupResponse`
        """
        model = EnvelopePlaygroundVoiceLookupResponse()
        if include_optional:
            return EnvelopePlaygroundVoiceLookupResponse(
                data = zarnite.models.playground_voice_lookup_response.PlaygroundVoiceLookupResponse(
                    org_id = '', 
                    user_id = '', 
                    category = '', 
                    source = '', 
                    livekit_stack = '', 
                    tts_provider = '', 
                    voice_access = '', 
                    voices = [
                        ''
                        ], ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopePlaygroundVoiceLookupResponse(
                data = zarnite.models.playground_voice_lookup_response.PlaygroundVoiceLookupResponse(
                    org_id = '', 
                    user_id = '', 
                    category = '', 
                    source = '', 
                    livekit_stack = '', 
                    tts_provider = '', 
                    voice_access = '', 
                    voices = [
                        ''
                        ], ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopePlaygroundVoiceLookupResponse(self):
        """Test EnvelopePlaygroundVoiceLookupResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
