# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.envelope_learner_score_response import EnvelopeLearnerScoreResponse

class TestEnvelopeLearnerScoreResponse(unittest.TestCase):
    """EnvelopeLearnerScoreResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvelopeLearnerScoreResponse:
        """Test EnvelopeLearnerScoreResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvelopeLearnerScoreResponse`
        """
        model = EnvelopeLearnerScoreResponse()
        if include_optional:
            return EnvelopeLearnerScoreResponse(
                data = zarnite.models.learner_score_response.LearnerScoreResponse(
                    learner_id = '', 
                    score = 56, 
                    cefr_level = '', 
                    breakdown = null, 
                    recommendation = '', 
                    assessed_at = '', 
                    rubric_type = '', 
                    rubric_reasoning = '', 
                    evaluation_mode = '', ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', )
            )
        else:
            return EnvelopeLearnerScoreResponse(
                data = zarnite.models.learner_score_response.LearnerScoreResponse(
                    learner_id = '', 
                    score = 56, 
                    cefr_level = '', 
                    breakdown = null, 
                    recommendation = '', 
                    assessed_at = '', 
                    rubric_type = '', 
                    rubric_reasoning = '', 
                    evaluation_mode = '', ),
                meta = zarnite.models.meta.Meta(
                    request_id = '', ),
        )
        """

    def testEnvelopeLearnerScoreResponse(self):
        """Test EnvelopeLearnerScoreResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
