# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.playground_session_response import PlaygroundSessionResponse

class TestPlaygroundSessionResponse(unittest.TestCase):
    """PlaygroundSessionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlaygroundSessionResponse:
        """Test PlaygroundSessionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlaygroundSessionResponse`
        """
        model = PlaygroundSessionResponse()
        if include_optional:
            return PlaygroundSessionResponse(
                session_id = '',
                session_kind = '',
                is_billable = True,
                room_name = '',
                participant_identity = '',
                participant_name = '',
                user_id = '',
                thread_id = '',
                resumed_from_session_id = '',
                resume_supported = True,
                max_duration_s = 56,
                recommended_resume_after_s = 56,
                voice = zarnite.models.playground_voice_config.PlaygroundVoiceConfig(
                    voice_id = '', 
                    locale = '', 
                    pitch = 1.337, 
                    speaking_rate = 1.337, ),
                voice_quota = { },
                routing_category = '',
                livekit_stack = '',
                tts_provider = '',
                voice_access = '',
                livekit = zarnite.models.live_kit_details.LiveKitDetails(
                    url = '', 
                    token = '', ),
                expires_at = ''
            )
        else:
            return PlaygroundSessionResponse(
                session_id = '',
                session_kind = '',
                is_billable = True,
                room_name = '',
                participant_identity = '',
                participant_name = '',
                user_id = '',
                thread_id = '',
                max_duration_s = 56,
                recommended_resume_after_s = 56,
                livekit = zarnite.models.live_kit_details.LiveKitDetails(
                    url = '', 
                    token = '', ),
                expires_at = '',
        )
        """

    def testPlaygroundSessionResponse(self):
        """Test PlaygroundSessionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
