# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zarnite.models.knowledge_delete_response import KnowledgeDeleteResponse

class TestKnowledgeDeleteResponse(unittest.TestCase):
    """KnowledgeDeleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KnowledgeDeleteResponse:
        """Test KnowledgeDeleteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KnowledgeDeleteResponse`
        """
        model = KnowledgeDeleteResponse()
        if include_optional:
            return KnowledgeDeleteResponse(
                document_id = '',
                chunks_deleted = 56,
                deleted = True
            )
        else:
            return KnowledgeDeleteResponse(
                document_id = '',
                chunks_deleted = 56,
        )
        """

    def testKnowledgeDeleteResponse(self):
        """Test KnowledgeDeleteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
