# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from zarnite.models.guardrails_config import GuardrailsConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentUpdate(BaseModel):
    """
    AgentUpdate
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Updated agent name")
    behavior_id: Optional[StrictStr] = Field(default=None, description="Updated behavior/profile identifier")
    description: Optional[StrictStr] = Field(default=None, description="Updated agent description")
    api_key_id: Optional[StrictStr] = Field(default=None, description="Updated API key binding")
    assigned_learners: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Updated assigned learner count")
    status: Optional[StrictStr] = Field(default=None, description="Updated operational status")
    language: Optional[StrictStr] = Field(default=None, description="Updated language")
    languages: Optional[List[StrictStr]] = Field(default=None, description="Updated language list")
    system_prompt: Optional[StrictStr] = Field(default=None, description="Updated system prompt")
    tone: Optional[StrictStr] = Field(default=None, description="Updated tone")
    strictness: Optional[StrictStr] = Field(default=None, description="Updated strictness")
    guardrails: Optional[GuardrailsConfig] = Field(default=None, description="Updated structured guardrail rules")
    enable_live_playground: Optional[StrictBool] = Field(default=None, description="Updated playground toggle")
    voice: Optional[StrictStr] = Field(default=None, description="Updated voice")
    enable_knowledge_base: Optional[StrictBool] = Field(default=None, description="Updated knowledge base toggle")
    __properties: ClassVar[List[str]] = ["name", "behavior_id", "description", "api_key_id", "assigned_learners", "status", "language", "languages", "system_prompt", "tone", "strictness", "guardrails", "enable_live_playground", "voice", "enable_knowledge_base"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'disabled', 'retired']):
            raise ValueError("must be one of enum values ('active', 'disabled', 'retired')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of guardrails
        if self.guardrails:
            _dict['guardrails'] = self.guardrails.to_dict()
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if behavior_id (nullable) is None
        # and model_fields_set contains the field
        if self.behavior_id is None and "behavior_id" in self.model_fields_set:
            _dict['behavior_id'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if api_key_id (nullable) is None
        # and model_fields_set contains the field
        if self.api_key_id is None and "api_key_id" in self.model_fields_set:
            _dict['api_key_id'] = None

        # set to None if assigned_learners (nullable) is None
        # and model_fields_set contains the field
        if self.assigned_learners is None and "assigned_learners" in self.model_fields_set:
            _dict['assigned_learners'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if languages (nullable) is None
        # and model_fields_set contains the field
        if self.languages is None and "languages" in self.model_fields_set:
            _dict['languages'] = None

        # set to None if system_prompt (nullable) is None
        # and model_fields_set contains the field
        if self.system_prompt is None and "system_prompt" in self.model_fields_set:
            _dict['system_prompt'] = None

        # set to None if tone (nullable) is None
        # and model_fields_set contains the field
        if self.tone is None and "tone" in self.model_fields_set:
            _dict['tone'] = None

        # set to None if strictness (nullable) is None
        # and model_fields_set contains the field
        if self.strictness is None and "strictness" in self.model_fields_set:
            _dict['strictness'] = None

        # set to None if guardrails (nullable) is None
        # and model_fields_set contains the field
        if self.guardrails is None and "guardrails" in self.model_fields_set:
            _dict['guardrails'] = None

        # set to None if enable_live_playground (nullable) is None
        # and model_fields_set contains the field
        if self.enable_live_playground is None and "enable_live_playground" in self.model_fields_set:
            _dict['enable_live_playground'] = None

        # set to None if voice (nullable) is None
        # and model_fields_set contains the field
        if self.voice is None and "voice" in self.model_fields_set:
            _dict['voice'] = None

        # set to None if enable_knowledge_base (nullable) is None
        # and model_fields_set contains the field
        if self.enable_knowledge_base is None and "enable_knowledge_base" in self.model_fields_set:
            _dict['enable_knowledge_base'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "behavior_id": obj.get("behavior_id"),
            "description": obj.get("description"),
            "api_key_id": obj.get("api_key_id"),
            "assigned_learners": obj.get("assigned_learners"),
            "status": obj.get("status"),
            "language": obj.get("language"),
            "languages": obj.get("languages"),
            "system_prompt": obj.get("system_prompt"),
            "tone": obj.get("tone"),
            "strictness": obj.get("strictness"),
            "guardrails": GuardrailsConfig.from_dict(obj["guardrails"]) if obj.get("guardrails") is not None else None,
            "enable_live_playground": obj.get("enable_live_playground"),
            "voice": obj.get("voice"),
            "enable_knowledge_base": obj.get("enable_knowledge_base")
        })
        return _obj


