# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ApiKeyCreateResponse(BaseModel):
    """
    Returned only on creation — contains the one-time raw key.
    """ # noqa: E501
    id: StrictStr = Field(description="API key identifier")
    org_id: StrictStr = Field(description="Organization scope", alias="orgId")
    name: StrictStr = Field(description="Key name")
    prefix: StrictStr = Field(description="Key prefix for identification (e.g. 'zrn_abc123')")
    raw_key: StrictStr = Field(description="Full API key — shown only once on creation", alias="rawKey")
    scopes: List[StrictStr] = Field(description="Permission scopes")
    rate_limit: StrictInt = Field(description="Rate limit (req/min)", alias="rateLimit")
    is_active: Optional[StrictBool] = Field(default=True, description="Whether key is active", alias="isActive")
    created_at: datetime = Field(description="Creation timestamp", alias="createdAt")
    __properties: ClassVar[List[str]] = ["id", "orgId", "name", "prefix", "rawKey", "scopes", "rateLimit", "isActive", "createdAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiKeyCreateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiKeyCreateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "orgId": obj.get("orgId"),
            "name": obj.get("name"),
            "prefix": obj.get("prefix"),
            "rawKey": obj.get("rawKey"),
            "scopes": obj.get("scopes"),
            "rateLimit": obj.get("rateLimit"),
            "isActive": obj.get("isActive") if obj.get("isActive") is not None else True,
            "createdAt": obj.get("createdAt")
        })
        return _obj


