# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BehaviorResponse(BaseModel):
    """
    BehaviorResponse
    """ # noqa: E501
    id: StrictStr = Field(description="Behavior identifier")
    org_id: StrictStr = Field(description="Owning organization", alias="orgId")
    name: StrictStr = Field(description="Behavior name")
    description: Optional[StrictStr] = Field(default=None, description="Behavior description")
    system_prompt: Optional[StrictStr] = Field(default=None, description="Core instruction prompt", alias="systemPrompt")
    tone: Optional[StrictStr] = Field(default=None, description="Tone setting")
    strictness: Optional[StrictStr] = Field(default=None, description="Strictness setting")
    language: Optional[StrictStr] = Field(default=None, description="Language")
    languages: Optional[List[StrictStr]] = Field(default=None, description="Preferred language list")
    guardrails: Optional[Dict[str, Any]] = Field(default=None, description="Structured guardrail rules")
    voice: Optional[StrictStr] = Field(default=None, description="Voice setting")
    is_default: Optional[StrictBool] = Field(default=False, description="Whether this is the org default", alias="isDefault")
    created_at: datetime = Field(description="Creation timestamp", alias="createdAt")
    updated_at: datetime = Field(description="Last update timestamp", alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "orgId", "name", "description", "systemPrompt", "tone", "strictness", "language", "languages", "guardrails", "voice", "isDefault", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BehaviorResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if system_prompt (nullable) is None
        # and model_fields_set contains the field
        if self.system_prompt is None and "system_prompt" in self.model_fields_set:
            _dict['systemPrompt'] = None

        # set to None if tone (nullable) is None
        # and model_fields_set contains the field
        if self.tone is None and "tone" in self.model_fields_set:
            _dict['tone'] = None

        # set to None if strictness (nullable) is None
        # and model_fields_set contains the field
        if self.strictness is None and "strictness" in self.model_fields_set:
            _dict['strictness'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if guardrails (nullable) is None
        # and model_fields_set contains the field
        if self.guardrails is None and "guardrails" in self.model_fields_set:
            _dict['guardrails'] = None

        # set to None if voice (nullable) is None
        # and model_fields_set contains the field
        if self.voice is None and "voice" in self.model_fields_set:
            _dict['voice'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BehaviorResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "orgId": obj.get("orgId"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "systemPrompt": obj.get("systemPrompt"),
            "tone": obj.get("tone"),
            "strictness": obj.get("strictness"),
            "language": obj.get("language"),
            "languages": obj.get("languages"),
            "guardrails": obj.get("guardrails"),
            "voice": obj.get("voice"),
            "isDefault": obj.get("isDefault") if obj.get("isDefault") is not None else False,
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


