# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DashboardOverviewResponse(BaseModel):
    """
    DashboardOverviewResponse
    """ # noqa: E501
    kpis: Dict[str, Any] = Field(description="Overview KPI payload")
    system_status: Dict[str, Any] = Field(description="System health summary", alias="systemStatus")
    usage_trends: Dict[str, Any] = Field(description="Daily, weekly, and monthly chart series", alias="usageTrends")
    progress_distribution: Optional[List[Optional[Dict[str, Any]]]] = Field(default=None, description="Learner proficiency distribution", alias="progressDistribution")
    progression_delta_pct: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Optional progression delta percentage", alias="progressionDeltaPct")
    progression_summary: Optional[StrictStr] = Field(default=None, description="Optional progression summary text", alias="progressionSummary")
    agent_activity: Optional[List[Optional[Dict[str, Any]]]] = Field(default=None, description="Top agent activity entries", alias="agentActivity")
    top_error: Optional[Dict[str, Any]] = Field(default=None, description="Top error category summary", alias="topError")
    __properties: ClassVar[List[str]] = ["kpis", "systemStatus", "usageTrends", "progressDistribution", "progressionDeltaPct", "progressionSummary", "agentActivity", "topError"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DashboardOverviewResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if progression_delta_pct (nullable) is None
        # and model_fields_set contains the field
        if self.progression_delta_pct is None and "progression_delta_pct" in self.model_fields_set:
            _dict['progressionDeltaPct'] = None

        # set to None if progression_summary (nullable) is None
        # and model_fields_set contains the field
        if self.progression_summary is None and "progression_summary" in self.model_fields_set:
            _dict['progressionSummary'] = None

        # set to None if top_error (nullable) is None
        # and model_fields_set contains the field
        if self.top_error is None and "top_error" in self.model_fields_set:
            _dict['topError'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DashboardOverviewResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kpis": obj.get("kpis"),
            "systemStatus": obj.get("systemStatus"),
            "usageTrends": obj.get("usageTrends"),
            "progressDistribution": obj.get("progressDistribution"),
            "progressionDeltaPct": obj.get("progressionDeltaPct"),
            "progressionSummary": obj.get("progressionSummary"),
            "agentActivity": obj.get("agentActivity"),
            "topError": obj.get("topError")
        })
        return _obj


