# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DocHit(BaseModel):
    """
    A single document chunk retrieved during memory/KB search.
    """ # noqa: E501
    source_file: Optional[StrictStr] = Field(default=None, description="Source file name", alias="sourceFile")
    scope: Optional[StrictStr] = Field(default=None, description="kb scope: agent or organization")
    relevance_score: Union[StrictFloat, StrictInt] = Field(description="Cosine similarity score (0-1, higher is better)", alias="relevanceScore")
    preview: StrictStr = Field(description="Truncated document content")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Full chunk metadata")
    __properties: ClassVar[List[str]] = ["sourceFile", "scope", "relevanceScore", "preview", "metadata"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocHit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if source_file (nullable) is None
        # and model_fields_set contains the field
        if self.source_file is None and "source_file" in self.model_fields_set:
            _dict['sourceFile'] = None

        # set to None if scope (nullable) is None
        # and model_fields_set contains the field
        if self.scope is None and "scope" in self.model_fields_set:
            _dict['scope'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocHit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sourceFile": obj.get("sourceFile"),
            "scope": obj.get("scope"),
            "relevanceScore": obj.get("relevanceScore"),
            "preview": obj.get("preview"),
            "metadata": obj.get("metadata")
        })
        return _obj


