# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class KnowledgeDocument(BaseModel):
    """
    A single knowledge base document (represents a group of chunks from one file).
    """ # noqa: E501
    document_id: StrictStr = Field(description="Stable identifier for this document (derived from source_file + scope)", alias="documentId")
    source_file: StrictStr = Field(description="Original uploaded filename", alias="sourceFile")
    scope: StrictStr = Field(description="Whether this document belongs to an agent KB or org-wide KB")
    org_id: StrictStr = Field(description="Organization scope", alias="orgId")
    agent_id: Optional[StrictStr] = Field(default=None, description="Agent scope (null for org-wide documents)", alias="agentId")
    chunk_count: StrictInt = Field(description="Number of vector chunks stored for this document", alias="chunkCount")
    uploaded_by: Optional[StrictStr] = Field(default=None, description="User who uploaded this document", alias="uploadedBy")
    created_at: Optional[StrictStr] = Field(default=None, description="Earliest chunk creation time (approximate upload time)", alias="createdAt")
    __properties: ClassVar[List[str]] = ["documentId", "sourceFile", "scope", "orgId", "agentId", "chunkCount", "uploadedBy", "createdAt"]

    @field_validator('scope')
    def scope_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['agent', 'organization']):
            raise ValueError("must be one of enum values ('agent', 'organization')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KnowledgeDocument from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if agent_id (nullable) is None
        # and model_fields_set contains the field
        if self.agent_id is None and "agent_id" in self.model_fields_set:
            _dict['agentId'] = None

        # set to None if uploaded_by (nullable) is None
        # and model_fields_set contains the field
        if self.uploaded_by is None and "uploaded_by" in self.model_fields_set:
            _dict['uploadedBy'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['createdAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KnowledgeDocument from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "documentId": obj.get("documentId"),
            "sourceFile": obj.get("sourceFile"),
            "scope": obj.get("scope"),
            "orgId": obj.get("orgId"),
            "agentId": obj.get("agentId"),
            "chunkCount": obj.get("chunkCount"),
            "uploadedBy": obj.get("uploadedBy"),
            "createdAt": obj.get("createdAt")
        })
        return _obj


