# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class KnowledgeUploadResponse(BaseModel):
    """
    KnowledgeUploadResponse
    """ # noqa: E501
    status: StrictStr = Field(description="Upload outcome")
    scope: StrictStr = Field(description="Knowledge base scope that received the file")
    org_id: StrictStr = Field(description="Organization scope", alias="orgId")
    agent_id: Optional[StrictStr] = Field(default=None, description="Agent scope when uploading to an agent KB", alias="agentId")
    kb_target_agent_id: StrictStr = Field(description="Agent identifier actually stored in KB metadata", alias="kbTargetAgentId")
    user_id: Optional[StrictStr] = Field(default=None, description="Optional user attribution stored on uploaded chunks", alias="userId")
    file: StrictStr = Field(description="Uploaded filename")
    chunks_indexed: StrictInt = Field(description="Number of chunks inserted into the vector store", alias="chunksIndexed")
    chunk_limit_applied: StrictBool = Field(description="Whether upload chunk cap truncated the document", alias="chunkLimitApplied")
    __properties: ClassVar[List[str]] = ["status", "scope", "orgId", "agentId", "kbTargetAgentId", "userId", "file", "chunksIndexed", "chunkLimitApplied"]

    @field_validator('scope')
    def scope_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['agent', 'organization']):
            raise ValueError("must be one of enum values ('agent', 'organization')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KnowledgeUploadResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if agent_id (nullable) is None
        # and model_fields_set contains the field
        if self.agent_id is None and "agent_id" in self.model_fields_set:
            _dict['agentId'] = None

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['userId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KnowledgeUploadResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "scope": obj.get("scope"),
            "orgId": obj.get("orgId"),
            "agentId": obj.get("agentId"),
            "kbTargetAgentId": obj.get("kbTargetAgentId"),
            "userId": obj.get("userId"),
            "file": obj.get("file"),
            "chunksIndexed": obj.get("chunksIndexed"),
            "chunkLimitApplied": obj.get("chunkLimitApplied")
        })
        return _obj


