# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from zarnite.models.learner_activity_event import LearnerActivityEvent
from zarnite.models.learner_response import LearnerResponse
from zarnite.models.learner_score_response import LearnerScoreResponse
from zarnite.models.learner_stats_response import LearnerStatsResponse
from zarnite.models.learner_summary_response import LearnerSummaryResponse
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LearnerMetadataResponse(BaseModel):
    """
    LearnerMetadataResponse
    """ # noqa: E501
    learner: LearnerResponse = Field(description="Safe learner profile metadata")
    stats: LearnerStatsResponse = Field(description="Aggregated usage and session stats")
    score: LearnerScoreResponse = Field(description="Current CEFR/progression score")
    summary: LearnerSummaryResponse = Field(description="Personalized learner summary")
    recent_activity: Optional[List[LearnerActivityEvent]] = Field(default=None, description="Recent voice session activity", alias="recentActivity")
    __properties: ClassVar[List[str]] = ["learner", "stats", "score", "summary", "recentActivity"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LearnerMetadataResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of learner
        if self.learner:
            _dict['learner'] = self.learner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of stats
        if self.stats:
            _dict['stats'] = self.stats.to_dict()
        # override the default output from pydantic by calling `to_dict()` of score
        if self.score:
            _dict['score'] = self.score.to_dict()
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in recent_activity (list)
        _items = []
        if self.recent_activity:
            for _item_recent_activity in self.recent_activity:
                _items.append(_item_recent_activity.to_dict() if _item_recent_activity is not None else None)
            _dict['recentActivity'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LearnerMetadataResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "learner": LearnerResponse.from_dict(obj["learner"]) if obj.get("learner") is not None else None,
            "stats": LearnerStatsResponse.from_dict(obj["stats"]) if obj.get("stats") is not None else None,
            "score": LearnerScoreResponse.from_dict(obj["score"]) if obj.get("score") is not None else None,
            "summary": LearnerSummaryResponse.from_dict(obj["summary"]) if obj.get("summary") is not None else None,
            "recentActivity": [LearnerActivityEvent.from_dict(_item) for _item in obj["recentActivity"]] if obj.get("recentActivity") is not None else None
        })
        return _obj


