# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LearnerStatsResponse(BaseModel):
    """
    LearnerStatsResponse
    """ # noqa: E501
    total_sessions: StrictInt = Field(description="Total voice sessions for this learner", alias="totalSessions")
    avg_duration_minutes: Union[StrictFloat, StrictInt] = Field(description="Average session duration in minutes", alias="avgDurationMinutes")
    avg_latency_ms: Union[StrictFloat, StrictInt] = Field(description="Average STT/TTS latency in milliseconds", alias="avgLatencyMs")
    est_inference_cost_per_session: Union[StrictFloat, StrictInt] = Field(description="Estimated inference cost per session (USD)", alias="estInferenceCostPerSession")
    total_tokens_used: StrictInt = Field(description="Total tokens consumed across all sessions", alias="totalTokensUsed")
    last_session_at: Optional[StrictStr] = Field(default=None, description="ISO timestamp of the most recent session", alias="lastSessionAt")
    __properties: ClassVar[List[str]] = ["totalSessions", "avgDurationMinutes", "avgLatencyMs", "estInferenceCostPerSession", "totalTokensUsed", "lastSessionAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LearnerStatsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if last_session_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_session_at is None and "last_session_at" in self.model_fields_set:
            _dict['lastSessionAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LearnerStatsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "totalSessions": obj.get("totalSessions"),
            "avgDurationMinutes": obj.get("avgDurationMinutes"),
            "avgLatencyMs": obj.get("avgLatencyMs"),
            "estInferenceCostPerSession": obj.get("estInferenceCostPerSession"),
            "totalTokensUsed": obj.get("totalTokensUsed"),
            "lastSessionAt": obj.get("lastSessionAt")
        })
        return _obj


