# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from zarnite.models.learner_feedback_metrics import LearnerFeedbackMetrics
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LearnerLongitudinalFeedbackResponse(BaseModel):
    """
    LearnerLongitudinalFeedbackResponse
    """ # noqa: E501
    learner_id: StrictStr = Field(description="Learner identifier", alias="learnerId")
    learner_name: StrictStr = Field(description="Learner display name", alias="learnerName")
    sessions_analyzed: StrictInt = Field(description="Number of recent sessions included", alias="sessionsAnalyzed")
    conversation_window: StrictStr = Field(description="Conversation window label", alias="conversationWindow")
    narrative: StrictStr = Field(description="Concise longitudinal feedback paragraph")
    metrics: LearnerFeedbackMetrics = Field(description="Current and previous learning signals")
    strengths: Optional[List[Optional[StrictStr]]] = Field(default=None, description="Top positive learner signals")
    improvement_areas: Optional[List[Optional[StrictStr]]] = Field(default=None, description="Top improvement areas", alias="improvementAreas")
    recommended_next_step: StrictStr = Field(description="Suggested action for the next session", alias="recommendedNextStep")
    recent_topics: Optional[List[Optional[StrictStr]]] = Field(default=None, description="Recent topic keywords", alias="recentTopics")
    generated_at: StrictStr = Field(description="ISO timestamp when feedback was generated", alias="generatedAt")
    evaluation_mode: Optional[StrictStr] = Field(default=None, description="Feedback generation mode, e.g. heuristic or llm_hybrid", alias="evaluationMode")
    rubric_type: Optional[StrictStr] = Field(default=None, description="Evaluation rubric used for the feedback", alias="rubricType")
    rubric_reasoning: Optional[StrictStr] = Field(default=None, description="Short explanation of why the rubric was selected", alias="rubricReasoning")
    evaluation_criteria: Optional[List[Dict[str, StrictStr]]] = Field(default=None, description="Frontend-ready rubric criteria used for the evaluation", alias="evaluationCriteria")
    progression_comparison: Optional[Dict[str, Any]] = Field(default=None, description="Comparison of the latest part of the window against the older part", alias="progressionComparison")
    __properties: ClassVar[List[str]] = ["learnerId", "learnerName", "sessionsAnalyzed", "conversationWindow", "narrative", "metrics", "strengths", "improvementAreas", "recommendedNextStep", "recentTopics", "generatedAt", "evaluationMode", "rubricType", "rubricReasoning", "evaluationCriteria", "progressionComparison"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LearnerLongitudinalFeedbackResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metrics
        if self.metrics:
            _dict['metrics'] = self.metrics.to_dict()
        # set to None if evaluation_mode (nullable) is None
        # and model_fields_set contains the field
        if self.evaluation_mode is None and "evaluation_mode" in self.model_fields_set:
            _dict['evaluationMode'] = None

        # set to None if rubric_type (nullable) is None
        # and model_fields_set contains the field
        if self.rubric_type is None and "rubric_type" in self.model_fields_set:
            _dict['rubricType'] = None

        # set to None if rubric_reasoning (nullable) is None
        # and model_fields_set contains the field
        if self.rubric_reasoning is None and "rubric_reasoning" in self.model_fields_set:
            _dict['rubricReasoning'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LearnerLongitudinalFeedbackResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "learnerId": obj.get("learnerId"),
            "learnerName": obj.get("learnerName"),
            "sessionsAnalyzed": obj.get("sessionsAnalyzed"),
            "conversationWindow": obj.get("conversationWindow"),
            "narrative": obj.get("narrative"),
            "metrics": LearnerFeedbackMetrics.from_dict(obj["metrics"]) if obj.get("metrics") is not None else None,
            "strengths": obj.get("strengths"),
            "improvementAreas": obj.get("improvementAreas"),
            "recommendedNextStep": obj.get("recommendedNextStep"),
            "recentTopics": obj.get("recentTopics"),
            "generatedAt": obj.get("generatedAt"),
            "evaluationMode": obj.get("evaluationMode"),
            "rubricType": obj.get("rubricType"),
            "rubricReasoning": obj.get("rubricReasoning"),
            "evaluationCriteria": obj.get("evaluationCriteria"),
            "progressionComparison": obj.get("progressionComparison")
        })
        return _obj


