# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from zarnite.models.score_breakdown import ScoreBreakdown
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LearnerScoreResponse(BaseModel):
    """
    LearnerScoreResponse
    """ # noqa: E501
    learner_id: StrictStr = Field(description="Learner identifier", alias="learnerId")
    score: StrictInt = Field(description="Overall proficiency score (0-100)")
    cefr_level: StrictStr = Field(description="CEFR level (A1-C2)", alias="cefrLevel")
    breakdown: ScoreBreakdown = Field(description="Per-dimension score breakdown")
    recommendation: StrictStr = Field(description="AI-generated recommendation text")
    assessed_at: StrictStr = Field(description="ISO timestamp of assessment", alias="assessedAt")
    rubric_type: Optional[StrictStr] = Field(default=None, description="Evaluation rubric used for scoring", alias="rubricType")
    rubric_reasoning: Optional[StrictStr] = Field(default=None, description="Short explanation of why the rubric was selected", alias="rubricReasoning")
    evaluation_mode: Optional[StrictStr] = Field(default=None, description="Scoring mode, e.g. heuristic or llm_hybrid", alias="evaluationMode")
    __properties: ClassVar[List[str]] = ["learnerId", "score", "cefrLevel", "breakdown", "recommendation", "assessedAt", "rubricType", "rubricReasoning", "evaluationMode"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LearnerScoreResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of breakdown
        if self.breakdown:
            _dict['breakdown'] = self.breakdown.to_dict()
        # set to None if rubric_type (nullable) is None
        # and model_fields_set contains the field
        if self.rubric_type is None and "rubric_type" in self.model_fields_set:
            _dict['rubricType'] = None

        # set to None if rubric_reasoning (nullable) is None
        # and model_fields_set contains the field
        if self.rubric_reasoning is None and "rubric_reasoning" in self.model_fields_set:
            _dict['rubricReasoning'] = None

        # set to None if evaluation_mode (nullable) is None
        # and model_fields_set contains the field
        if self.evaluation_mode is None and "evaluation_mode" in self.model_fields_set:
            _dict['evaluationMode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LearnerScoreResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "learnerId": obj.get("learnerId"),
            "score": obj.get("score"),
            "cefrLevel": obj.get("cefrLevel"),
            "breakdown": ScoreBreakdown.from_dict(obj["breakdown"]) if obj.get("breakdown") is not None else None,
            "recommendation": obj.get("recommendation"),
            "assessedAt": obj.get("assessedAt"),
            "rubricType": obj.get("rubricType"),
            "rubricReasoning": obj.get("rubricReasoning"),
            "evaluationMode": obj.get("evaluationMode")
        })
        return _obj


