# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OrgRagSessionLimitUpdateRequest(BaseModel):
    """
    OrgRagSessionLimitUpdateRequest
    """ # noqa: E501
    enabled: StrictBool = Field(description="Whether org-level monthly RAG session limits are enforced")
    monthly_session_limit: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Maximum distinct RAG sessions (thread_id) allowed per month when enabled")
    monthly_user_session_limit: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Maximum distinct RAG sessions per user per month when enabled")
    monthly_user_time_limit_minutes: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Maximum cumulative RAG active time per user per month, in minutes, when enabled")
    __properties: ClassVar[List[str]] = ["enabled", "monthly_session_limit", "monthly_user_session_limit", "monthly_user_time_limit_minutes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrgRagSessionLimitUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if monthly_session_limit (nullable) is None
        # and model_fields_set contains the field
        if self.monthly_session_limit is None and "monthly_session_limit" in self.model_fields_set:
            _dict['monthly_session_limit'] = None

        # set to None if monthly_user_session_limit (nullable) is None
        # and model_fields_set contains the field
        if self.monthly_user_session_limit is None and "monthly_user_session_limit" in self.model_fields_set:
            _dict['monthly_user_session_limit'] = None

        # set to None if monthly_user_time_limit_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.monthly_user_time_limit_minutes is None and "monthly_user_time_limit_minutes" in self.model_fields_set:
            _dict['monthly_user_time_limit_minutes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrgRagSessionLimitUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled"),
            "monthly_session_limit": obj.get("monthly_session_limit"),
            "monthly_user_session_limit": obj.get("monthly_user_session_limit"),
            "monthly_user_time_limit_minutes": obj.get("monthly_user_time_limit_minutes")
        })
        return _obj


