# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OrganizationAnalyticsResponse(BaseModel):
    """
    OrganizationAnalyticsResponse
    """ # noqa: E501
    range: StrictStr = Field(description="Selected range label")
    view: StrictStr = Field(description="Selected analytics lens")
    classes: Optional[List[Optional[StrictStr]]] = Field(default=None, description="Available class filters")
    date_ranges: Optional[List[Optional[StrictStr]]] = Field(default=None, description="Available date ranges", alias="dateRanges")
    institution: Dict[str, Any] = Field(description="Institution overview payload")
    agents: Optional[List[Optional[Dict[str, Any]]]] = Field(default=None, description="Agent performance payload")
    students: Optional[List[Optional[Dict[str, Any]]]] = Field(default=None, description="Student list payload")
    student_detail: Optional[Dict[str, Any]] = Field(default=None, description="Selected student detail payload", alias="studentDetail")
    __properties: ClassVar[List[str]] = ["range", "view", "classes", "dateRanges", "institution", "agents", "students", "studentDetail"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrganizationAnalyticsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if student_detail (nullable) is None
        # and model_fields_set contains the field
        if self.student_detail is None and "student_detail" in self.model_fields_set:
            _dict['studentDetail'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrganizationAnalyticsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "range": obj.get("range"),
            "view": obj.get("view"),
            "classes": obj.get("classes"),
            "dateRanges": obj.get("dateRanges"),
            "institution": obj.get("institution"),
            "agents": obj.get("agents"),
            "students": obj.get("students"),
            "studentDetail": obj.get("studentDetail")
        })
        return _obj


