# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from zarnite.models.playground_metrics_event import PlaygroundMetricsEvent
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PlaygroundMetricsResponse(BaseModel):
    """
    PlaygroundMetricsResponse
    """ # noqa: E501
    session_id: StrictStr = Field(description="Session identifier", alias="sessionId")
    session_kind: StrictStr = Field(description="Session classification", alias="sessionKind")
    status: StrictStr = Field(description="Current session status")
    duration_s: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Session duration in seconds", alias="durationS")
    total_events: StrictInt = Field(description="Total events recorded", alias="totalEvents")
    events: Optional[List[PlaygroundMetricsEvent]] = Field(default=None, description="Session events (latency, STT/TTS, etc.)")
    __properties: ClassVar[List[str]] = ["sessionId", "sessionKind", "status", "durationS", "totalEvents", "events"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlaygroundMetricsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in events (list)
        _items = []
        if self.events:
            for _item_events in self.events:
                _items.append(_item_events.to_dict() if _item_events is not None else None)
            _dict['events'] = _items
        # set to None if duration_s (nullable) is None
        # and model_fields_set contains the field
        if self.duration_s is None and "duration_s" in self.model_fields_set:
            _dict['durationS'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlaygroundMetricsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sessionId": obj.get("sessionId"),
            "sessionKind": obj.get("sessionKind"),
            "status": obj.get("status"),
            "durationS": obj.get("durationS"),
            "totalEvents": obj.get("totalEvents"),
            "events": [PlaygroundMetricsEvent.from_dict(_item) for _item in obj["events"]] if obj.get("events") is not None else None
        })
        return _obj


