# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from zarnite.models.live_kit_details import LiveKitDetails
from zarnite.models.playground_voice_config_output import PlaygroundVoiceConfigOutput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PlaygroundSessionResponse(BaseModel):
    """
    PlaygroundSessionResponse
    """ # noqa: E501
    session_id: StrictStr = Field(description="Created session identifier", alias="sessionId")
    session_kind: StrictStr = Field(description="Session classification", alias="sessionKind")
    is_billable: StrictBool = Field(description="Whether this session counts toward billing", alias="isBillable")
    room_name: StrictStr = Field(description="LiveKit room name", alias="roomName")
    participant_identity: StrictStr = Field(description="Participant identity string", alias="participantIdentity")
    participant_name: StrictStr = Field(description="Participant display name", alias="participantName")
    user_id: StrictStr = Field(description="Resolved user for the session", alias="userId")
    thread_id: StrictStr = Field(description="Resolved conversation thread", alias="threadId")
    resumed_from_session_id: Optional[StrictStr] = Field(default=None, description="Previous session id when resuming", alias="resumedFromSessionId")
    resume_supported: Optional[StrictBool] = Field(default=True, description="Whether the client can resume the same thread in a fresh session", alias="resumeSupported")
    max_duration_s: StrictInt = Field(description="Max duration for the current session in seconds", alias="maxDurationS")
    recommended_resume_after_s: StrictInt = Field(description="Recommended client-side reconnect time for seamless continuation", alias="recommendedResumeAfterS")
    voice: Optional[PlaygroundVoiceConfigOutput] = Field(default=None, description="Resolved voice config")
    voice_quota: Optional[Dict[str, Any]] = Field(default=None, description="Billable voice quota snapshot for this session", alias="voiceQuota")
    routing_category: Optional[StrictStr] = Field(default=None, description="Resolved routing category used for this session", alias="routingCategory")
    livekit_stack: Optional[StrictStr] = Field(default=None, description="Resolved LiveKit stack used for token minting", alias="livekitStack")
    tts_provider: Optional[StrictStr] = Field(default=None, description="Resolved TTS provider label", alias="ttsProvider")
    voice_access: Optional[StrictStr] = Field(default=None, description="Resolved voice entitlement tier (free|paid)", alias="voiceAccess")
    livekit: LiveKitDetails = Field(description="LiveKit connection details")
    expires_at: StrictStr = Field(description="Token expiry ISO timestamp", alias="expiresAt")
    __properties: ClassVar[List[str]] = ["sessionId", "sessionKind", "isBillable", "roomName", "participantIdentity", "participantName", "userId", "threadId", "resumedFromSessionId", "resumeSupported", "maxDurationS", "recommendedResumeAfterS", "voice", "voiceQuota", "routingCategory", "livekitStack", "ttsProvider", "voiceAccess", "livekit", "expiresAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlaygroundSessionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of voice
        if self.voice:
            _dict['voice'] = self.voice.to_dict()
        # override the default output from pydantic by calling `to_dict()` of livekit
        if self.livekit:
            _dict['livekit'] = self.livekit.to_dict()
        # set to None if resumed_from_session_id (nullable) is None
        # and model_fields_set contains the field
        if self.resumed_from_session_id is None and "resumed_from_session_id" in self.model_fields_set:
            _dict['resumedFromSessionId'] = None

        # set to None if voice (nullable) is None
        # and model_fields_set contains the field
        if self.voice is None and "voice" in self.model_fields_set:
            _dict['voice'] = None

        # set to None if voice_quota (nullable) is None
        # and model_fields_set contains the field
        if self.voice_quota is None and "voice_quota" in self.model_fields_set:
            _dict['voiceQuota'] = None

        # set to None if routing_category (nullable) is None
        # and model_fields_set contains the field
        if self.routing_category is None and "routing_category" in self.model_fields_set:
            _dict['routingCategory'] = None

        # set to None if livekit_stack (nullable) is None
        # and model_fields_set contains the field
        if self.livekit_stack is None and "livekit_stack" in self.model_fields_set:
            _dict['livekitStack'] = None

        # set to None if tts_provider (nullable) is None
        # and model_fields_set contains the field
        if self.tts_provider is None and "tts_provider" in self.model_fields_set:
            _dict['ttsProvider'] = None

        # set to None if voice_access (nullable) is None
        # and model_fields_set contains the field
        if self.voice_access is None and "voice_access" in self.model_fields_set:
            _dict['voiceAccess'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlaygroundSessionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sessionId": obj.get("sessionId"),
            "sessionKind": obj.get("sessionKind"),
            "isBillable": obj.get("isBillable"),
            "roomName": obj.get("roomName"),
            "participantIdentity": obj.get("participantIdentity"),
            "participantName": obj.get("participantName"),
            "userId": obj.get("userId"),
            "threadId": obj.get("threadId"),
            "resumedFromSessionId": obj.get("resumedFromSessionId"),
            "resumeSupported": obj.get("resumeSupported") if obj.get("resumeSupported") is not None else True,
            "maxDurationS": obj.get("maxDurationS"),
            "recommendedResumeAfterS": obj.get("recommendedResumeAfterS"),
            "voice": PlaygroundVoiceConfigOutput.from_dict(obj["voice"]) if obj.get("voice") is not None else None,
            "voiceQuota": obj.get("voiceQuota"),
            "routingCategory": obj.get("routingCategory"),
            "livekitStack": obj.get("livekitStack"),
            "ttsProvider": obj.get("ttsProvider"),
            "voiceAccess": obj.get("voiceAccess"),
            "livekit": LiveKitDetails.from_dict(obj["livekit"]) if obj.get("livekit") is not None else None,
            "expiresAt": obj.get("expiresAt")
        })
        return _obj


