# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from zarnite.models.playground_transcript_message import PlaygroundTranscriptMessage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PlaygroundSessionTranscriptResponse(BaseModel):
    """
    PlaygroundSessionTranscriptResponse
    """ # noqa: E501
    session_id: StrictStr = Field(description="Voice session identifier", alias="sessionId")
    thread_id: StrictStr = Field(description="Conversation thread identifier", alias="threadId")
    session_kind: StrictStr = Field(description="Session classification", alias="sessionKind")
    status: StrictStr = Field(description="Current session status")
    started_at: Optional[StrictStr] = Field(default=None, description="Session start time", alias="startedAt")
    ended_at: Optional[StrictStr] = Field(default=None, description="Session end time", alias="endedAt")
    last_activity_at: Optional[StrictStr] = Field(default=None, description="Most recent activity time", alias="lastActivityAt")
    livekit_room_name: Optional[StrictStr] = Field(default=None, description="LiveKit room backing the session", alias="livekitRoomName")
    messages: Optional[List[PlaygroundTranscriptMessage]] = Field(default=None, description="Ordered transcript messages for the session")
    __properties: ClassVar[List[str]] = ["sessionId", "threadId", "sessionKind", "status", "startedAt", "endedAt", "lastActivityAt", "livekitRoomName", "messages"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlaygroundSessionTranscriptResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in messages (list)
        _items = []
        if self.messages:
            for _item_messages in self.messages:
                _items.append(_item_messages.to_dict() if _item_messages is not None else None)
            _dict['messages'] = _items
        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['startedAt'] = None

        # set to None if ended_at (nullable) is None
        # and model_fields_set contains the field
        if self.ended_at is None and "ended_at" in self.model_fields_set:
            _dict['endedAt'] = None

        # set to None if last_activity_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_activity_at is None and "last_activity_at" in self.model_fields_set:
            _dict['lastActivityAt'] = None

        # set to None if livekit_room_name (nullable) is None
        # and model_fields_set contains the field
        if self.livekit_room_name is None and "livekit_room_name" in self.model_fields_set:
            _dict['livekitRoomName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlaygroundSessionTranscriptResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sessionId": obj.get("sessionId"),
            "threadId": obj.get("threadId"),
            "sessionKind": obj.get("sessionKind"),
            "status": obj.get("status"),
            "startedAt": obj.get("startedAt"),
            "endedAt": obj.get("endedAt"),
            "lastActivityAt": obj.get("lastActivityAt"),
            "livekitRoomName": obj.get("livekitRoomName"),
            "messages": [PlaygroundTranscriptMessage.from_dict(_item) for _item in obj["messages"]] if obj.get("messages") is not None else None
        })
        return _obj


