# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UserSummaryResponse(BaseModel):
    """
    UserSummaryResponse
    """ # noqa: E501
    org_id: StrictStr = Field(alias="orgId")
    agent_id: StrictStr = Field(alias="agentId")
    user_id: StrictStr = Field(alias="userId")
    messages: Dict[str, Any] = Field(description="Message counts (total, user, assistant)")
    first_activity: Optional[StrictStr] = Field(default=None, description="ISO timestamp of first activity", alias="firstActivity")
    last_activity: Optional[StrictStr] = Field(default=None, description="ISO timestamp of last activity", alias="lastActivity")
    sessions: Dict[str, Any] = Field(description="Session stats (total, active, avg_duration_s, last_session)")
    most_active_hours: List[Any] = Field(description="Top 5 most active hours", alias="mostActiveHours")
    __properties: ClassVar[List[str]] = ["orgId", "agentId", "userId", "messages", "firstActivity", "lastActivity", "sessions", "mostActiveHours"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserSummaryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if first_activity (nullable) is None
        # and model_fields_set contains the field
        if self.first_activity is None and "first_activity" in self.model_fields_set:
            _dict['firstActivity'] = None

        # set to None if last_activity (nullable) is None
        # and model_fields_set contains the field
        if self.last_activity is None and "last_activity" in self.model_fields_set:
            _dict['lastActivity'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserSummaryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "orgId": obj.get("orgId"),
            "agentId": obj.get("agentId"),
            "userId": obj.get("userId"),
            "messages": obj.get("messages"),
            "firstActivity": obj.get("firstActivity"),
            "lastActivity": obj.get("lastActivity"),
            "sessions": obj.get("sessions"),
            "mostActiveHours": obj.get("mostActiveHours")
        })
        return _obj


