# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from zarnite.models.voice_runtime_final_feedback import VoiceRuntimeFinalFeedback
from zarnite.models.voice_runtime_transcript_payload import VoiceRuntimeTranscriptPayload
from zarnite.models.voice_runtime_usage_payload import VoiceRuntimeUsagePayload
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VoiceRuntimeCloseRequest(BaseModel):
    """
    VoiceRuntimeCloseRequest
    """ # noqa: E501
    event_id: StrictStr = Field(description="Idempotency-safe worker event identifier")
    session_id: StrictStr = Field(description="Voice session identifier")
    org_id: StrictStr = Field(description="Organization scope")
    agent_id: StrictStr = Field(description="Agent scope")
    user_id: StrictStr = Field(description="Learner/user identifier")
    thread_id: StrictStr = Field(description="Conversation thread identifier")
    room_name: Optional[StrictStr] = Field(default=None, description="LiveKit room name")
    started_at: Optional[datetime] = Field(default=None, description="Worker-observed start time")
    ended_at: Optional[datetime] = Field(default=None, description="Worker-observed end time")
    duration_seconds: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Final session duration in seconds")
    status: Optional[StrictStr] = Field(default='completed', description="Worker-reported final session status")
    usage: Optional[VoiceRuntimeUsagePayload] = Field(default=None, description="Usage payload")
    transcript: Optional[VoiceRuntimeTranscriptPayload] = Field(default=None, description="Transcript payload")
    final_feedback: Optional[VoiceRuntimeFinalFeedback] = Field(default=None, description="Optional final feedback summary")
    __properties: ClassVar[List[str]] = ["event_id", "session_id", "org_id", "agent_id", "user_id", "thread_id", "room_name", "started_at", "ended_at", "duration_seconds", "status", "usage", "transcript", "final_feedback"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VoiceRuntimeCloseRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transcript
        if self.transcript:
            _dict['transcript'] = self.transcript.to_dict()
        # override the default output from pydantic by calling `to_dict()` of final_feedback
        if self.final_feedback:
            _dict['final_feedback'] = self.final_feedback.to_dict()
        # set to None if room_name (nullable) is None
        # and model_fields_set contains the field
        if self.room_name is None and "room_name" in self.model_fields_set:
            _dict['room_name'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        # set to None if ended_at (nullable) is None
        # and model_fields_set contains the field
        if self.ended_at is None and "ended_at" in self.model_fields_set:
            _dict['ended_at'] = None

        # set to None if duration_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.duration_seconds is None and "duration_seconds" in self.model_fields_set:
            _dict['duration_seconds'] = None

        # set to None if final_feedback (nullable) is None
        # and model_fields_set contains the field
        if self.final_feedback is None and "final_feedback" in self.model_fields_set:
            _dict['final_feedback'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VoiceRuntimeCloseRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_id": obj.get("event_id"),
            "session_id": obj.get("session_id"),
            "org_id": obj.get("org_id"),
            "agent_id": obj.get("agent_id"),
            "user_id": obj.get("user_id"),
            "thread_id": obj.get("thread_id"),
            "room_name": obj.get("room_name"),
            "started_at": obj.get("started_at"),
            "ended_at": obj.get("ended_at"),
            "duration_seconds": obj.get("duration_seconds"),
            "status": obj.get("status") if obj.get("status") is not None else 'completed',
            "usage": VoiceRuntimeUsagePayload.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
            "transcript": VoiceRuntimeTranscriptPayload.from_dict(obj["transcript"]) if obj.get("transcript") is not None else None,
            "final_feedback": VoiceRuntimeFinalFeedback.from_dict(obj["final_feedback"]) if obj.get("final_feedback") is not None else None
        })
        return _obj


