# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VoiceRuntimeCloseResponse(BaseModel):
    """
    VoiceRuntimeCloseResponse
    """ # noqa: E501
    accepted: Optional[StrictBool] = Field(default=True, description="Whether the worker event was accepted")
    session_persisted: Optional[StrictBool] = Field(default=False, description="Whether the session close was persisted locally", alias="sessionPersisted")
    analytics_enqueued: Optional[StrictBool] = Field(default=False, description="Whether learner analytics refresh was triggered", alias="analyticsEnqueued")
    billing_enqueued: Optional[StrictBool] = Field(default=False, description="Whether usage/billing payload was persisted for downstream processing", alias="billingEnqueued")
    credit_wallet: Optional[Dict[str, Any]] = Field(default=None, description="Optional month credit wallet snapshot after debit", alias="creditWallet")
    __properties: ClassVar[List[str]] = ["accepted", "sessionPersisted", "analyticsEnqueued", "billingEnqueued", "creditWallet"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VoiceRuntimeCloseResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if credit_wallet (nullable) is None
        # and model_fields_set contains the field
        if self.credit_wallet is None and "credit_wallet" in self.model_fields_set:
            _dict['creditWallet'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VoiceRuntimeCloseResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accepted": obj.get("accepted") if obj.get("accepted") is not None else True,
            "sessionPersisted": obj.get("sessionPersisted") if obj.get("sessionPersisted") is not None else False,
            "analyticsEnqueued": obj.get("analyticsEnqueued") if obj.get("analyticsEnqueued") is not None else False,
            "billingEnqueued": obj.get("billingEnqueued") if obj.get("billingEnqueued") is not None else False,
            "creditWallet": obj.get("creditWallet")
        })
        return _obj


