# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VoiceRuntimeHistoryThread(BaseModel):
    """
    VoiceRuntimeHistoryThread
    """ # noqa: E501
    thread_id: StrictStr = Field(description="Thread identifier", alias="threadId")
    learner_name: Optional[StrictStr] = Field(default=None, description="Learner name carried in stored snapshots", alias="learnerName")
    latest_question: Optional[StrictStr] = Field(default=None, description="Latest learner question in that thread", alias="latestQuestion")
    latest_answer: Optional[StrictStr] = Field(default=None, description="Latest assistant answer in that thread", alias="latestAnswer")
    last_message_at: Optional[StrictStr] = Field(default=None, description="Last message timestamp for the thread", alias="lastMessageAt")
    __properties: ClassVar[List[str]] = ["threadId", "learnerName", "latestQuestion", "latestAnswer", "lastMessageAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VoiceRuntimeHistoryThread from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if learner_name (nullable) is None
        # and model_fields_set contains the field
        if self.learner_name is None and "learner_name" in self.model_fields_set:
            _dict['learnerName'] = None

        # set to None if latest_question (nullable) is None
        # and model_fields_set contains the field
        if self.latest_question is None and "latest_question" in self.model_fields_set:
            _dict['latestQuestion'] = None

        # set to None if latest_answer (nullable) is None
        # and model_fields_set contains the field
        if self.latest_answer is None and "latest_answer" in self.model_fields_set:
            _dict['latestAnswer'] = None

        # set to None if last_message_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_message_at is None and "last_message_at" in self.model_fields_set:
            _dict['lastMessageAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VoiceRuntimeHistoryThread from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "threadId": obj.get("threadId"),
            "learnerName": obj.get("learnerName"),
            "latestQuestion": obj.get("latestQuestion"),
            "latestAnswer": obj.get("latestAnswer"),
            "lastMessageAt": obj.get("lastMessageAt")
        })
        return _obj


