# coding: utf-8

"""
    Zarnite Core API

    Agent lifecycle, behaviors, knowledge, learners, API keys, deployments, playground, memory, usage, analytics.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from zarnite.models.voice_runtime_agent_context import VoiceRuntimeAgentContext
from zarnite.models.voice_runtime_history_context import VoiceRuntimeHistoryContext
from zarnite.models.voice_runtime_learner_context import VoiceRuntimeLearnerContext
from zarnite.models.voice_runtime_rag_context import VoiceRuntimeRagContext
from zarnite.models.voice_runtime_session_ref import VoiceRuntimeSessionRef
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VoiceRuntimeBootstrapResponse(BaseModel):
    """
    VoiceRuntimeBootstrapResponse
    """ # noqa: E501
    session: VoiceRuntimeSessionRef = Field(description="Session identifiers")
    learner: VoiceRuntimeLearnerContext = Field(description="Learner context")
    agent_runtime: VoiceRuntimeAgentContext = Field(description="Resolved runtime behavior and language configuration", alias="agentRuntime")
    history: VoiceRuntimeHistoryContext = Field(description="Compact history context")
    rag: VoiceRuntimeRagContext = Field(description="Knowledge availability summary")
    __properties: ClassVar[List[str]] = ["session", "learner", "agentRuntime", "history", "rag"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VoiceRuntimeBootstrapResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of session
        if self.session:
            _dict['session'] = self.session.to_dict()
        # override the default output from pydantic by calling `to_dict()` of learner
        if self.learner:
            _dict['learner'] = self.learner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of agent_runtime
        if self.agent_runtime:
            _dict['agentRuntime'] = self.agent_runtime.to_dict()
        # override the default output from pydantic by calling `to_dict()` of history
        if self.history:
            _dict['history'] = self.history.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rag
        if self.rag:
            _dict['rag'] = self.rag.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VoiceRuntimeBootstrapResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "session": VoiceRuntimeSessionRef.from_dict(obj["session"]) if obj.get("session") is not None else None,
            "learner": VoiceRuntimeLearnerContext.from_dict(obj["learner"]) if obj.get("learner") is not None else None,
            "agentRuntime": VoiceRuntimeAgentContext.from_dict(obj["agentRuntime"]) if obj.get("agentRuntime") is not None else None,
            "history": VoiceRuntimeHistoryContext.from_dict(obj["history"]) if obj.get("history") is not None else None,
            "rag": VoiceRuntimeRagContext.from_dict(obj["rag"]) if obj.get("rag") is not None else None
        })
        return _obj


